### ISSUE TITLE
Floating Point Support

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#10]
An existing soft float library should be compiled for the platform. Floating point operations should be made to call out to this library. The library should be included in the package of compiler support routines. The link process should be arranged to ensure that they are not included in the binary unless they are actually used.

**Comment by mlund** [comment]
For reference, commander x16 has a floating point library:
- [Documentation](https://github.com/commanderx16/x16-docs/blob/master/X16%20Reference%20-%2005%20-%20Math%20Library.md)
- [Source](https://github.com/commanderx16/x16-rom/tree/master/math)
- [Licence](https://github.com/commanderx16/x16-rom/blob/master/LICENSE.md)

**Comment by johnwbyrd** [comment]
https://github.com/rweather/berkeley-softfloat-3-6502

**Comment by mysterymath** [comment]
Blocked by #420

**Comment by mysterymath** [comment]
Now that #420 is finished, completing this consists of making the existing printf functions weak, adding a printf_f library that prints floating point, and enabling llvm-test-suite tests that were disabled due to missing floating point.

**Comment by mysterymath** [comment]
Completed as of the most recent release.
