### ISSUE TITLE
Modifiers don't work outside instructions

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#112]
It looks like modifiers like mos16hi don't work in directives:
```
.byte mos16hi(adr16)
```

```
error: unexpected token
```

This sort of thing comes up when building tables in ASM to be relocated by the linker. You may want to separate the high bytes and the low bytes into two separate tables, but the linker still needs to fix up both separately.

From a cursory examination, it looks like LLVM does have hooks to do this: MCTargetAsmParser::parsePrimaryExpr gets called when .byte directives are being parsed.

We'd probably need to plumb more logic through the fixup handling. I accidentally generated the equivalent of this when trying to add jump tables; it looks like the MCMosExpr variant wasn't properly translated into low-level relocation types.

**Comment by iss000** [comment]
Thanks for the good work on llvm-mos!
May I ask for fix or workaround on this bug because it's really crucial  for any real work with tables which include relocation addresses.

**Comment by mysterymath** [comment]
This actually appears to work; the syntax is just `.byte adr16@mos16hi`.
Looking at the other targets, it looks like this is the expected way to specify the relocation type for general expressions; the instruction variants are added for backwards compatibility and as a nicety. The adr16@mos16hi syntax should work there too.

I'll update the documentation on this one. Feel free to reopen this if this ends up not actually working; I've verified this the best I can using the compiler tests, but there may still be some aspects of this that aren't 100% correct yet.

**Comment by iss000** [comment]
>  `.byte adr16@mos16hi`
This works for me just fine. Thank you very much!
