### ISSUE TITLE
 Jump Tables

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#13]
LLVM can be made to emit jump tables for dense portions of switch statements. This allows constant time dispatch instead of a logarithmic number of comparisons.

The 6502 could implement this using either the RTS trick or an indirect JMP. LLVM needs to be tuned to only emit jump tables when they would be more efficient than the replaced comparisons; indirect branches are fairly cheap, so this may be "almost always."

**Comment by johnwbyrd** [comment]
Background info:

https://llvm.org/devmtg/2015-10/slides/Wennborg-SwitchLowering.pdf
https://llvm.org/docs/LangRef.html#switch-instruction
https://slideslive.com/38902416/switch-lowering-improvements?subdomain=false&locale=cs
https://www.youtube.com/watch?v=gMqSinyL8uk

**Comment by mysterymath** [comment]
Apparently globalisel just emits these; doesn't look like there's much way to control whether or not they're emitted for switch-like code. This is thus bumped up to DeRisk, since it's needed for printf to get the test suite working.
