### ISSUE TITLE
support for llvm.trap()

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos#132]
While compiling code that may panic rustc generates `llvm.trap()` intrinsic https://llvm.org/docs/LangRef.html#llvm-trap-intrinsic 
Currently it results with following compilation error:

```
LLVM ERROR: unable to legalize instruction: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.trap) (in function: main)
```

As 6502 doesn't have dedicated `trap` opcode we probably should emit some `trap` libcall instead

**Comment by mysterymath** [comment]
From the docs, it looks like we should lower this to abort(). Shouldn't be too difficult.
