### ISSUE TITLE
Whole-program zero page allocation

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#174]
Presently, LLVM-MOS can only automatically make use of 32 bytes of the zero page. This is mostly fine on platforms where the OS and/or DOS consumes most of the zero page, but pretty bad more baremetal targets like the NES, or even the C64.

It's still possible to define pointers, linker scripts, or hand-written assembly to access the zero page, but ideally the compiler would be able to automatically assign global and local variables to the region.

This feature would be need careful design; the available zero page differs from platform to platform, and compiler use of the zero page would need to play nice with programmer use.

**Comment by AGPX** [comment]
I use to write video game for C64 and I get rid of Kernal and Basic ROMs, so I use zero page addresses from 2 to 255.
I warmly suggest to allow this possibility, because this can optimize speed and memory quite a lot.

**Comment by epi** [comment]
Wouldn't this boil down to specifying how many zero page locations are available to the compiler, followed by mapping them to the concrete ranges?
