### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by AGPX** [llvm-mos/llvm-mos#175]
Hello,

I've tried to compile the following simple C code just to do a test:

```
int main(void) {
  unsigned char *dst = (unsigned char *)0x400;
  const unsigned char *src = (unsigned char *)0x500;

  unsigned int i = 500;
  do {
  	*(dst++) = *(src++);
  } while ((--i) != 0);

  return 0;
}
```

the compiled code (with `mos-c64-clang++ -Wl,--lto-emit-asm -O3 .\mytest.c -o mytest.prg`) is as follows:

```
        .text
        .file   "ld-temp.o"
        .section        .text.main,"ax",@progbits
        .globl  main
        .type   main,@function
main:
        lda     #0
        ldy     #0
        sta     mos8(__rc2)
        sta     mos8(__rc3)
.LBB0_1:
        lda     #0
        clc
        adc     mos8(__rc2)
        tax
        lda     #1
        bcs     .LBB0_3
        lda     #0
.LBB0_3:
        sta     mos8(__rc7)
        lda     #4
        adc     mos8(__rc3)
        stx     mos8(__rc4)
        sta     mos8(__rc5)
        stx     mos8(__rc6)
        lda     #5
        ldx     mos8(__rc7)
        cpx     #1
        adc     mos8(__rc3)
        sta     mos8(__rc7)
        lda     (mos8(__rc6)),y
        sta     (mos8(__rc4)),y
        ldx     mos8(__rc2)
        lda     mos8(__rc3)
        inx
        beq     .LBB0_6
        stx     mos8(__rc2)
        sta     mos8(__rc3)
        cmp     #1
        bne     .LBB0_1
.LBB0_5:
        stx     mos8(__rc2)
        sta     mos8(__rc3)
        cpx     #244
        bne     .LBB0_1
        jmp     .LBB0_7
.LBB0_6:
        clc
        adc     #1
        stx     mos8(__rc2)
        sta     mos8(__rc3)
        cmp     #1
        bne     .LBB0_1
        jmp     .LBB0_5
.LBB0_7:
        ldx     #0
        lda     #0
        rts
.Lfunc_end0:
        .size   main, .Lfunc_end0-main
```

It looks quite not optimized. As reference, I've compared it with the output of another C compiler for 6502:

```
main: {
    .label dst = 4
    .label src = 2
    .label i = 6
    lda #<$1f4
    sta.z i
    lda #>$1f4
    sta.z i+1
    lda #<$400
    sta.z dst
    lda #>$400
    sta.z dst+1
    lda #<$500
    sta.z src
    lda #>$500
    sta.z src+1
  __b1:
    // *(dst++) = *(src++)
    ldy #0
    lda (src),y
    sta (dst),y
    // *(dst++) = *(src++);
    inc.z dst
    bne !+
    inc.z dst+1
  !:
    inc.z src
    bne !+
    inc.z src+1
  !:
    // while ((--i) != 0)
    lda.z i
    bne !+
    dec.z i+1
  !:
    dec.z i
    lda.z i
    ora.z i+1
    bne __b1
    // }
    rts
}
```

It looks really better. Are there some optimization flags that I can add to produce a better code?

**Comment by mysterymath** [comment]
-Os tends to produce better code on the 6502; -O3 sacrifices size for speed, so the compiler is willing to, e.g., duplicate a section of code to avoid executing a single branch instruction.

With -Os, the code above gives the following. There's still definitely ways to improve this; we can't claim to produce better code than other C compilers in all circumstances. The compiler is still under active development, and we do have to fight with LLVM's assumptions and limitations a bit. We're gradually working on peeling back those limitations, one at a time.

That being said, I'm mostly working on making sure the compiler is easy to port and develop for; it already generates "okay" code, and a truly arbitrary amount of time can be sunk into polishing every aspect of it. I'm hoping to return to code generation once we've got a solid guide published for how to port the compiler to support new target platforms.

```
main:
        lda     #0
        ldy     #0
        sta     mos8(__rc2)
        sta     mos8(__rc3)
.LBB0_1:
        lda     #0
        clc
        adc     mos8(__rc2)
        tax
        lda     #1
        bcs     .LBB0_3
        lda     #0
.LBB0_3:
        sta     mos8(__rc7)
        lda     #4
        adc     mos8(__rc3)
        stx     mos8(__rc4)
        sta     mos8(__rc5)
        stx     mos8(__rc6)
        lda     #5
        ldx     mos8(__rc7)
        cpx     #1
        adc     mos8(__rc3)
        sta     mos8(__rc7)
        lda     (mos8(__rc6)),y
        sta     (mos8(__rc4)),y
        ldx     mos8(__rc2)
        lda     mos8(__rc3)
        inx
        bne     .LBB0_5
        clc
        adc     #1
.LBB0_5:
        stx     mos8(__rc2)
        sta     mos8(__rc3)
        cmp     #1
        bne     .LBB0_1
        stx     mos8(__rc2)
        sta     mos8(__rc3)
        cpx     #244
        bne     .LBB0_1
        ldx     #0
        lda     #0
        rts

```

**Comment by mysterymath** [comment]
Please do leave this open BTW; I'd like to address this specific example once I get back around to it.

**Comment by mysterymath** [comment]
Did a quick dig into this; it looks like Loop Strength Reduction is confused about the costs here. It thinks it's cheaper to implement the loop as: for (int i = 0; i < 500; i++) { *dst[i] = *src[i]; }, but this requires two additions and an increment, vs two increments and a decrement. I'll have to go in and see specifically how it's computing the cost here; I might have to teach it that increments/decrements are cheaper than general additions/subtractions.

**Comment by AGPX** [comment]
Okay, this can probably be true for x86, but not for 6502. Just like branching which is heavier on x86 due to the cache, but still loop unrolling is good on 6502 too. So, yes, probably certains optimizations criteria must be reviewed for 6502.

**Comment by mysterymath** [comment]
Well, you may be happy to know that this example just kept giving; it pointed out some rather serious problems with our code generator, and sections of it are going to need to be rewritten.

The good news is I think I know how to do that. I hacked together a dramatically broken and incomplete version that works just for this one example, but the results were excellent (see below). There's still a couple things that could be improved, but they're just missing cleanup passes, which aren't as important as getting the main-line code generation right. It remains to be seen whether or not this generalizes well; I need to get the whole thing written up and ran against our benchmarking suite.

I'll post back once I've got more news. Take care!
```
main:                                   
  ldx #12
  ldy #-2
  sty mos8(__rc6)
  ldy #0
  sty mos8(__rc2)
  ldy #4
  sty mos8(__rc3)
  ldy #0
  sty mos8(__rc4)
  ldy #5
  sty mos8(__rc5)
  ldy #0
.LBB0_1:                                
  lda (mos8(__rc4)),y
  inc mos8(__rc4)
  bne .LBB0_3
  inc mos8(__rc5)
.LBB0_3:                                
  sta (mos8(__rc2)),y
  inc mos8(__rc2)
  bne .LBB0_5
  inc mos8(__rc3)
.LBB0_5:                                
  inx
  bne .LBB0_1
  inc mos8(__rc6)
  bne .LBB0_1
  ldx #0
  lda #0
  rts
```

**Comment by AGPX** [comment]
Wow, it looks by far better now (even better than the other compiler!). Keep the good work!

**Comment by mysterymath** [comment]
The final version of this ended up being the following. The optimization is now submitted, for a considerable win on certain benchmarks, and a slight regression on others (so it goes).
```
	.text
	.file	"bad.c"
	.globl	main                            ; -- Begin function main
	.type	main,@function
main:                                   ; @main
; %bb.0:                                ; %entry
	ldx	#12
	lda	#-2
	ldy	#0
	sty	mos8(__rc2)
	ldy	#4
	sty	mos8(__rc3)
	ldy	#0
	sty	mos8(__rc4)
	ldy	#5
	sty	mos8(__rc5)
	ldy	#0
	sta	mos8(__rc6)
.LBB0_1:                                ; %do.body
                                        ; =>This Inner Loop Header: Depth=1
	lda	(mos8(__rc4)),y
	inc	mos8(__rc4)
	bne	.LBB0_3
; %bb.2:                                ; %do.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	inc	mos8(__rc5)
.LBB0_3:                                ; %do.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	sta	(mos8(__rc2)),y
	inc	mos8(__rc2)
	bne	.LBB0_5
; %bb.4:                                ; %do.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	inc	mos8(__rc3)
.LBB0_5:                                ; %do.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	inx
	bne	.LBB0_1
; %bb.6:                                ; %do.body
                                        ;   in Loop: Header=BB0_1 Depth=1
	inc	mos8(__rc6)
	bne	.LBB0_1
; %bb.7:                                ; %do.end
	ldx	#0
	lda	#0
	rts
.Lfunc_end0:
	.size	main, .Lfunc_end0-main
                                        ; -- End function
	.ident	"clang version 15.0.0 (git@github.com:llvm-mos/llvm-mos.git 9afa47d0e1eabe67b307c5051d30ef2c3b0f012f)"
	.section	".note.GNU-stack","",@progbits
	.addrsig
```
