### ISSUE TITLE
printf() format %p produces unexpected result

### ISSUE THREAD

**Issue by smuehlst** [llvm-mos/llvm-mos#179]
I'm working on an llvm-mos-sdk port for the Ohio Scientific (OSI) platform. The work in progress can be found here:

https://github.com/smuehlst/llvm-mos-sdk

I don't know how to run a program with one of the other platforms or with the emulator, therefore I can't provide a standalone reproduction case, but I doubt that the observed problem is related to something in my clone of the llvm-mos-sdk repository.

How to reproduce:

I built the following test program:

```
#include <stdio.h>

int
main(void)
{
    putchar('A');

    printf("\r\nHello world with llvm-mos!\r\n");
    printf("\r\n");
    printf("HELLO, %s!\r\n", "PRINTF");
    printf("sizeof(char) %d\r\n", (int) sizeof(char));
    printf("sizeof(int) %d\r\n", (int) sizeof(int));
    printf("sizeof(void *) %d\r\n", (int) sizeof(void *));
    printf("sizeof(long) %d\r\n", (int) sizeof(long));
    printf("sizeof(long long) %d\r\n", (int) sizeof(long long));
    printf("address of main %p\r\n", (void *) main);
    printf("main as int 0x%X\r\n", (unsigned int) main);

    while (1);

    return 0;
}
```
The SDK and the program were build in "Debug" mode.

When I run the compiled executable in one of the available Ohio Scientific emulators, the following output is produced:

![image](https://user-images.githubusercontent.com/98944/165144973-c3c42a74-cc46-48a0-9d2e-60c04179bfe8.png)

Ignore the text "0200 A9". This is present because the screen is not cleared currently when the program is started from the OSI monitor program after loading.

The output looks correct except for the output with the "%p" format string for the address of the main program. As I verified with `llvm-objdump` the function call `printf("main as int 0x%X\r\n", (unsigned int) main);` prints the correct address 0x241, while the function call `printf("address of main %p\r\n", (void *) main);` produces the bogus address A518.

Expected behavior: Both `printf()` calls to print the address of `main()` printf the same address 241h.

**Comment by mysterymath** [comment]
Thanks for filing! Fixed by llvm-mos/llvm-mos-sdk@6e09309.
