### ISSUE TITLE
ERROR while building llvm

### ISSUE THREAD

**Issue by Sofianebouaziz1** [llvm-mos/llvm-mos#181]
Hello i'am facing an error while installing llvm.

Please check the log file.
[log.txt](https://github.com/llvm-mos/llvm-mos/files/8569873/log.txt)

I really need an anserw asap :( !.

**Comment by mysterymath** [comment]
From the log, it looks like you're trying to build the upstream LLVM project; this is a downstream backend for the 6502.
I think you're looking for llvm/llvm-project.

**Comment by Sofianebouaziz1** [comment]
What do you mean with 6502 ?

**Comment by Sofianebouaziz1** [comment]
@mysterymath  I actually fixed that error but another one occurs :

[ 44%] Linking CXX shared library ../../lib/libLTO.so
/usr/bin/ld : ../../lib/libLLVMARMCodeGen.a(ARMTargetMachine.cpp.o) : dans la fonction « (anonymous namespace)::ARMPassConfig::addPreSched2() » :
ARMTargetMachine.cpp:(.text._ZN12_GLOBAL__N_113ARMPassConfig12addPreSched2Ev+0x2b8) : référence indéfinie vers « llvm::createARMIndirectThunks() »
/usr/bin/ld : ARMTargetMachine.cpp:(.text._ZN12_GLOBAL__N_113ARMPassConfig12addPreSched2Ev+0x2cd) : référence indéfinie vers « llvm::createARMSLSHardeningPass() »
/usr/bin/ld : ../../lib/libLLVMARMCodeGen.a(ARMTargetMachine.cpp.o) : dans la fonction « LLVMInitializeARMTarget » :
ARMTargetMachine.cpp:(.text.LLVMInitializeARMTarget+0x12d) : référence indéfinie vers « llvm::initializeARMSLSHardeningPass(llvm::PassRegistry&) »
collect2: error: ld returned 1 exit status
make[2]: *** [tools/lto/CMakeFiles/LTO.dir/build.make:191 : lib/libLTO.so.13] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:25555 : tools/lto/CMakeFiles/LTO.dir/all] Erreur 2
make: *** [Makefile:152 : all] Erreur 2

Please can you provide me a solution I really need it

**Comment by mysterymath** [comment]
This is the wrong Github project. You want https://github.com/llvm/llvm-project
