### ISSUE TITLE
Refactoring fixit sweep, isel through AsmPrinter

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#2]
Now that development is proceeding in a joint codebase, code cleanliness, simplicity, and readability are a risk factor for the project.
A sweep of the codebase should be performed to simplify, refactor, and clean the implementation. It's worth taking minor performance hits for simplicity's sake, so long as those hits do not represent architectural hurdles to undo. These optimizations will be re-done in cost/benefit order after C99 has been reached; they were only in the De-Risk phase to ensure that they were possible, but the code doesn't need to carry their weight while it's being generalized.

Edit:
As a result of this factor, every newly-introduced concept should have an accompanying documentation comment. This includes pseudoinstructions, logical instructions, pseudoregisters, and code generation library routines, among others.

**Comment by johnwbyrd** [comment]
This is a good idea.  But it seems to be more like a principle of ongoing development, as opposed to a specific deliverable.  Because refactoring is, and ever will be, both necessary and ongoing, I'm closing this particular issue.  If particular things need to be refactored, they should pop up again as new issues.

**Comment by mysterymath** [comment]
While this is something that should happen in an ongoing fashion, too many of these items have piled up in my half of the codebase to fix incrementally at the rate we're accumulating new code. This issue is for a specific "fixit sweep" through the codebase, starting from the instruction selector (where it left off) and moving through to the end of the AsmPrinter. At the end of this, I'd expect a significant LOC reduction in the code generator, which should make successive tasks quicker.

**Comment by johnwbyrd** [comment]
When that happens, the AsmParser really ought to be rewritten.  It works, but it's unnecessarily verbose due to its AVR heritage, and could probably be done in far fewer lines of code.
