### ISSUE TITLE
mos-clang cannot assemble the assembly it generates

### ISSUE THREAD

**Issue by atn34** [llvm-mos/llvm-mos#206]
Example:
```
$ cat test.c 
int main() {}
$ mos-dodo-clang test.c -o test.s -Wl,--lto-emit-asm && mos-dodo-clang test.s
test.s:612:2: error: operand must be an 8 to 16 bit value (between 256 and 65535 inclusive)
        and     #-128
        ^
```

It's possible that emitting negative immediate values is the only problem, since the following seems to work:
```
$ mos-dodo-clang test.c -o - -Wl,--lto-emit-asm | sed 's/#-/#256-/g' > test.s && mos-dodo-clang test.s
```

**Comment by mysterymath** [comment]
I found another issue that we can tack on to this one. When the compiler generates Absolute,X and Absolute,Y instructions with constants <256, they will be be output as e.g. `asl $42,x`. If this were later assembled, it would be interpreted as a ZeroPage,X instruction, rather than the intended Absolute,X instruction. These have different behavior if base + index > 256.

**Comment by johnwbyrd** [comment]
The only solution to Daniel's problem that I can immediately think of, involves creating a number of new opcodes that encode to the Abs,X and Abs,Y instructions regardless of parameter length.  This solution feels ugly and wrong, however.  Is there a way we can avoid wrapping around address $100 as a feature?

**Comment by mysterymath** [comment]
Can we have these output as mos16(42),x? That should be unambiguously parsed as addr16, right?

I think what we're looking for is idempotency: that whatever opcode you output, that's the same opcode you get when you parse input. There may be many semantic forms that are all semantically equivalent, but you wouldn't need to have syntactic idempotency, just semantic.

**Comment by mysterymath** [comment]
Actually, it occurs to me that the only way we can ever see a 16-bit opcode with 8-bit constant value and no wrapping mos16() is if the compiler directly generates one in machine instruction lowering. There shouldn't be any assembly parse that can generate that. So this may just be a matter of making the compiler wrap the result with mos16 if it detects that the operand is an 8-bit constant.
