### ISSUE TITLE
Implement `wai` and `stp` instructions

### ISSUE THREAD

**Issue by atn34** [llvm-mos/llvm-mos#216]
These are instructions specific to the wdc 65c02: https://en.wikipedia.org/wiki/WDC_65C02#Low-power_modes, but that can't be used in assembly files currently.

**Comment by mysterymath** [comment]
Note that this task requires adding parsing and machine code generation for these instructions to LLVM-MOS; it's not just a matter of turning them on.

**Comment by mysterymath** [comment]
See also #54.

**Comment by alexschrod** [comment]
While we're waiting for these instructions to be added proper, is there any way to just *force* an opcode into the generated assembly? All I need is to stuff a `$DB` byte into where this `STP` should be:
```
.globl debug
debug:
    STP
    RTS
```
I tried writing `#$DB` in place of the `STP` but it didn't end up in the final executable.

The way I'm working around this now is by putting `NOP` in place of `STP` and then manually hex editing the final executable to put the right opcode in, but this is obviously very tedious and time consuming.

**Comment by atn34** [comment]
You can use the `.byte` directive, .e.g `.byte $CB` for `wai`
