### ISSUE TITLE
Incorrect addressing mode generated by assembler

### ISSUE THREAD

**Issue by davidgiven** [llvm-mos/llvm-mos#230]
I've found a really obscure issue where the wrong addressing mode is used to refer to an address _if_ the value is external _and_ if the value is part of an expression _and_ if there's a zero page segment above it _and_ if debugging is enabled...

```
.section .zp, "ax"
b: .fill 1

.text
main:
	lda external + 1
	lda external
```

...produces this:

```
$ mos-clang -c -Os -g test.S
$ llvm-objdump -dSr test.o
test.o:	file format elf32-mos

Disassembly of section .text:

00000000 <main>:
; 	lda external + 1
       0: a5 00        	lda	0
			00000001:  R_MOS_ADDR8	external+0x1
; 	lda external
       2: ad 00 00     	lda	0
			00000003:  R_MOS_ADDR16	external

Disassembly of section .zp:

00000000 <b>:
       0: 00           	brk
```

Removing the `-g` flag, changing the name of the initial data section, or removing the expression (as you can see above) causes the issue to go away.

```
clang version 16.0.0 (https://www.github.com/llvm-mos/llvm-mos.git 717c1afeb495e281df16326b65fe080abb69c264)
Target: mos
Thread model: posix
InstalledDir: /opt/bin
```

**Comment by mysterymath** [comment]
Huh, bizarre.

**Comment by davidgiven** [comment]
Here's another similar issue which I think is related:

```
.section .zp, "zax", @nobits
temp:             .byte 0

.text
    sta temp
    sta temp+0
```    

--->

```
$ mos-cpm65-clang -Os -c -o test.o test.S -I include/
$ llvm-objdump -dSr test.o
...
       0: 85 00        	sta	0
			00000001:  R_MOS_ADDR8	.zp
       2: 8d 00 00     	sta	0
			00000003:  R_MOS_ADDR16	.zp
```

Using an expression with `temp` causes 16-bit addressing. This one only shows up if I _don't_ use `-g`.

**Comment by davidgiven** [comment]
I've attempted to rebuild llvm-mos and try adding this to the unit tests; building it is more complicated than it should be because apparently my 32GB machine doesn't have enough memory to do a x8 parallel build of llvm (!). But I'm finding that out of the box, `check-all` fails (log attached below). Is this normal or does it suggest that something's wrong with my fork?

Assuming it's normal, I tried modifying `lld/test/ELF/mos-hello-world.s` so that the first code line reads `ldx #$0 ; CHECK: encoding: [0xa2,0x01]` and `check-lld` still fails to fail, so clearly I'm not doing something right. Is there anything I need to do other than modifying the test file and doing `ninja -C build check-lld`?

```
FAILED: tools/clang/bindings/python/tests/CMakeFiles/check-clang-python /home/dg/nonshared/llvm-mos/build/tools/clang/bindings/python/tests/CMakeFiles/check-clang-python 
cd /home/dg/nonshared/llvm-mos/clang/bindings/python && /usr/bin/cmake -E env CLANG_LIBRARY_PATH=/home/dg/nonshared/llvm-mos/build/lib /usr/bin/python3.10 -m unittest discover
............................F...........................................................................................F.....
======================================================================
FAIL: test_get_template_argument_unsigned_value (tests.cindex.test_cursor.TestCursor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dg/nonshared/llvm-mos/clang/bindings/python/tests/cindex/test_cursor.py", line 545, in test_get_template_argument_unsigned_value
    self.assertEqual(foos[1].get_template_argument_unsigned_value(0), 2 ** 32 - 7)
AssertionError: 65529 != 4294967289

======================================================================
FAIL: test_offset (tests.cindex.test_type.TestType)
Ensure Cursor.get_record_field_offset works in anonymous records
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dg/nonshared/llvm-mos/clang/bindings/python/tests/cindex/test_type.py", line 421, in test_offset
    self.assertEqual(teststruct.type.get_offset("bariton"), bariton)
AssertionError: 16 != 32

----------------------------------------------------------------------
Ran 126 tests in 1.319s
```

**Comment by mysterymath** [comment]
That test failure is decidedly outside anything we've touched in llvm-mos. I've definitely seen various flakes when running the test suite, both in continuous integration upstream and the llvm-mos project. It's reached the point where you can't actually trust presubmit test failures on the Phabricator code review.

You might try running your modified test manually using `llvm-lit`; you can then pick apart and debug specifically what's happening with your modifications.

**Comment by mysterymath** [comment]
This appears to have been due to a fairly unusual way to determining the underlying symbol for an expression; it involved examining the text of the original assembly. It looks like LLVM already has facilities for making this determination though, so I've rewritten that code to use it instead; that seems to have resolved the issue.

**Comment by davidgiven** [comment]
Tested --- it works. Thanks!
