### ISSUE TITLE
lld assertion failure

### ISSUE THREAD

**Issue by davidgiven** [llvm-mos/llvm-mos#232]
I have a code snippet which causes lld to fall over. This is with the c64 target, too, so I don't think it's my fault.

```
#include <stdint.h>

volatile char c;

static void printip(long precision)
{
    while (precision)
    {
        precision /= 10;
		c = precision;
    }
}

int main(int argc, const char* argv[])
{
    printip(1000LU);
}
```

--->

```
$ mos-c64-clang -Os -g test.c 
ld.lld: /home/dg/nonshared/llvm-mos/llvm/lib/CodeGen/RegisterBankInfo.cpp:523: bool llvm::RegisterBankInfo::PartialMapping::verify() const: Assertion `RegBank->getSize() >= Length && "Register bank too small for Mask"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/bin/ld.lld /tmp/test-2af8f7.o -plugin-opt=O2 -mllvm -force-precise-rotation-cost -mllvm -jump-inst-cost=6 -mllvm -force-loop-cold-block -mllvm -phi-node-folding-threshold=0 -mllvm -two-entry-phi-node-folding-threshold=0 -mllvm -align-large-globals=false -mllvm -disable-spill-hoist -mllvm -zp-avail=110 --gc-sections --sort-section=alignment -L/opt/pkg/llvm-mos/bin/../mos-platform/c64/lib -L/opt/pkg/llvm-mos/bin/../mos-platform/commodore/lib -L/opt/pkg/llvm-mos/bin/../mos-platform/common/lib -l:crt0.o -lcrt0 -lcrt -lc -Tlink.ld -o a.out
1.	Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.	Running pass 'RegBankSelect' on function '@main'
^C
```

(It actually then hangs and I have to ^C it.) This is with latest llvm-mos from git (or at least, as of a couple of hours ago). Interestingly, removing a zero from the constant parameter to `printip()` causes it to work.

**Comment by gandhi56** [comment]
I am using the latest compiler, seems to be compiling just fine for me.

**Comment by davidgiven** [comment]
I did build this myself. Is there a way to make cmake tell me what configuration flags I used? (Given by how slow it is I think there are a lot of assertions enabled, but I don't recall which ones.)

**Comment by gandhi56** [comment]
The complete config setup is specified in CMakeCache.txt.

**Comment by mysterymath** [comment]
I've got a full debug build on my end, and I wasn't able to reproduce this either.

**Comment by davidgiven** [comment]
It looks like it was this:

```
cmake -C clang/cmake/caches/MOS.cmake -S llvm -B build -DCMAKE_INSTALL_PREFIX=/opt/pkg/llvm-mos -DCMAKE_BUILD_TYPE=Debug
```

**Comment by mysterymath** [comment]
I'd definitely recommend using Ninja, it's pretty tremendously faster than make for projects the size of LLVM, and it's essentially the standard build system for those hacking on LLVM. It should still work on Make though of course; I'm trying to build a clean checkout of the compiler/SDK with that command (and make for the SDK), and I'll see if I can reproduce.

**Comment by mysterymath** [comment]
Just went through a fresh build using the command you provided and GNU make; can't reproduce on Arch Linux.

Only think I can think to try is to nuke your build directory and start again. At least I can provide the standard cocktail for speeding LLVM builds:
1. Install system clang, lld, and ccache.
2. `-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_ASM_COMPILER=clang`: Compile with clang.
3. `-DLLVM_USE_LINKER=lld`: Link with lld.
4. `-DLLVM_PARALLEL_LINK_JOBS=1`: Under ninja, don't run a link job in parallel with anything else.
5. `-DLLVM_CCACHE_BUILD=1`: Slightly slows down the first build, but can greatly speed rebuilds afterwards. Requires a fixed amount of additional disk space.
6. `-G Ninja`: Use ninja.
