### ISSUE TITLE
@llvm.fshl hangs compiler

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos#234]
To reproduce compile following program with -O2:
```
#include <stdio.h>

static inline unsigned int rotl16 (unsigned int n, unsigned int c)
{
  const unsigned int mask = (8 * sizeof(n) - 1);
  c &= mask;
  return (n<<c) | (n>>( (-c)&mask ));
}

int main() {
  volatile int n = 1;
  printf("%d\n", rotl16(0x8f, n));
}
```

**Comment by mysterymath** [comment]
It looks like I'd never actually gotten around to implementing rotation libcalls for variable amounts, and the naive lowering code didn't actually work.

The right way to fix this is to just implement rotation libcalls via loops, like we have with shifts.

**Comment by mysterymath** [comment]
I've issued a patch release for this issue: https://github.com/llvm-mos/llvm-mos-sdk/releases/tag/v0.10.1
