### ISSUE TITLE
Convert ca65 object files to llvm-mos ELF in llvm-objcopy.

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#239]
Having a build step available to convert ca65 object files to ELF object files would make it relatively straightforward to incorporate existing ca65 assembly files into an llvm-mos link. This would allow existing assembly "libraries" (typically standalone files) that make heavy use of ca65 features to be used with our SDK's relatively sophisticated linker system.

**Comment by chorman0773** [comment]
I'd note that some things will not be convertible. xo65 objects have far
more complex relocation options available than elf. I discovered this in
attempting to attach to my existing binary format structures.

**Comment by mysterymath** [comment]
This is specifically for the intermediate object files used by ca65 and ld65, not the o65 load-time relocatable object format. We also have considerable latitude to set up any additional relocations necessary to make this work, since our ELF extension is well-defined, but project-specific.

**Comment by chorman0773** [comment]
Yes, xo65 refers to that format use by the cc65 project in general. o65 is
closer to a.out and is quite well-behaved.

There are some issues that are fundamental to elf as well. xo65 allows, for
example, `foo+bar` as a relocation in the object file, where `foo` and
`bar` are both non-absolute symbols.

**Comment by mysterymath** [comment]
Ah, I wasn't familiar with the nomenclature; references to that as a filename are very scant in their documentation.

I don't think this creates any intrinsic difficulty, since ELF allows you to compose relocations. A pair of relocations could add two relative symbols to the same base address.

**Comment by chorman0773** [comment]
Can it mutiply or xor two symbols?

This is what I worked off of previously: https://github.com/Rapdorian/xo65

**Comment by mysterymath** [comment]
Sigh, thanks for the link; I hadn't expected that they'd put an entire expression grammar into their object file format.
I don't think it's fatal, but it will require some hackery. Off the top of my head, it may be possible to create a generalized ca65 expression grammar relocation that uses an auxiliary symbol containing the expression. But I'd need to get into the linker and see what's feasible.

**Comment by mysterymath** [comment]
I've spent some time working on this, and I think I have a strategy for making this a bit more hands-off.

The idea is this: slot external process calls to od65 and ld65 into the normal ELF linking process in LLD. There's already a quite a lot of infrastructure for handling odd input file formats in LLD; that's how the various types of object files, libraries, and bitcode compilation are all implemented. We could add another for xo65, then use the inspection capabilities already offered in od65 to produce an accounting of its symbols and sizes. That should be all that's required to lay out its sections. Then, relocating the section can invoke ld65 with a LLD-generated linker script to actually relocate the ca65 files and produce raw binaries. The raw binaries can then become the section contents, and the link would proceed from that point as normal.

For now, we'll end up with some very ca65-specific logic in LLD, but with quite clean cuts internally along API boundaries. It would still be much much less than picking apart xo65, and it should accordingly be much less brittle. A follow up would be to generalize this into an abstraction that could be used to slot in arbitrary processes to fill in this kind of information during a link, e.g. with a JSON API. This would allow us to generalize this to any other 6502 family linker we might like to support.

I'm doing work along these lines now; I'll post back here if anything new develops along the way.
