### ISSUE TITLE
Assembler support for "INC A", "INA", and LDA (zp),Y (capitalized)

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#241]
Some common assembly variants aren't supported in the llvm-mos assembler, which has led to some surprised discussion on the Commander X16 DIscord. If it's reasonable, it'd be nice to support the various common variant spellings of plain 6502 instructions.

**Comment by pfusik** [comment]
Do you mean some 6502 derivative? Plain 6502 doesn't have these instructions.

**Comment by mysterymath** [comment]
Yes, I edited the title accordingly. The increment A instruction is for the 65c02, while the capitalization issue affects all 6502 variants.

**Comment by mysterymath** [comment]
This should be fixed with @pfusik 's latest commit.
