### ISSUE TITLE
Inline asm branch to wrong location

### ISSUE THREAD

**Issue by pfusik** [llvm-mos/llvm-mos#243]
This is a follow-up to llvm-mos/llvm-mos-sdk#88.

Environment:

    C:\0\a8\llvm>install\bin\mos-atari8-clang --version
    clang version 16.0.0 (https://github.com/llvm-mos/llvm-mos.git dfee8229c859e8127cdc08b5abe2192d5a65d561)
    Target: mos
    Thread model: posix
    InstalledDir: C:/0/a8/llvm/install/bin
    Configuration file: C:/0/a8/llvm/install/bin/mos-atari8.cfg

Steps to reproduce:

    C:\0\a8\llvm>cat inline-asm-no-label.c
    int main() {
      unsigned char c;
      asm volatile(
        "ldx #0\n"
        "jsr $e456\n"
        "bmi error\n"
        : "=a"(c) : : "p", "a", "x", "y");
      return c == 0x9b ? '\n' : c;
    error:
      return -1;
    }

    C:\0\a8\llvm>install\bin\mos-atari8-clang -Os -Wall -o inline-asm-no-label.xex inline-asm-no-label.c
    inline-asm-no-label.c:9:1: warning: unused label 'error' [-Wunused-label]
    error:
    ^~~~~~
    1 warning generated.

    C:\0\a8\llvm>xebin d inline-asm-no-label.xex
    L2021   EQU $2021
    LE456   EQU $E456
            ORG $02E0
            DTA A(L2000)
            ORG $2000
    L2000   JSR L2011
            JMP L2007
    L2006   RTS
    L2007   STA L2021
            JSR L2006
            LDA L2021
            RTS
    L2011   LDX #$00
            JSR LE456
            BMI L2011
            LDX #$00
            CMP #$9B
            BNE L2020
            LDA #$0A
    L2020   RTS

Expected:

I don't know which one is correct, but I think it should be one of these:
a. `bmi error` jumps to the C label.
b. Fatal error for unknown asm label.

Actual:

`bmi error` jumps to `main`.

**Comment by mysterymath** [comment]
The GNU Assembler semantics doesn't consider it an error to reference a symbol not defined in the current .s file; these are made undefined references in the link. But the error symbol should be unresolved at link time, which should produce a link failure, but I've reproduced this locally, and as you say, it resolves to main.

**Comment by johnwbyrd** [comment]
Thanks Daniel!
