### ISSUE TITLE
Inline assembly reloads X

### ISSUE THREAD

**Issue by pfusik** [llvm-mos/llvm-mos#245]
Same environment and reproducer as in #244.

Expected:

`ldx #0` is emitted once.

Actual:

`ldx #0` is emitted twice. Correct, but suboptimal.

**Comment by mysterymath** [comment]
GCC-alike like LLVM don't perform any kind of introspection into inline assembly fragment; they're treated as black boxes completely described by the surrounding metadata. This is mostly by design, since the contents can be truly arbitrary strings, and the semantics are always straight textual inclusion.

**Comment by pfusik** [comment]
Oops, wrong reproducer, sorry! I believe the problem is still there with the current `main`:

    C:\0\a8\llvm>install\bin\mos-atari8-clang --version
    clang version 16.0.0 (https://github.com/llvm-mos/llvm-mos.git 361b5e36af30df63086956b4895445c5eba81065)
    Target: mos
    Thread model: posix
    InstalledDir: C:/0/a8/llvm/install/bin
    Configuration file: C:/0/a8/llvm/install/bin/mos-atari8.cfg

    C:\0\a8\llvm>cat reload-x.c
    int getchar() {
      *(unsigned *) 0x348 = 0;
      const unsigned char channel = 0;
      unsigned char c;
      asm volatile(
        "jsr $e456\n"
        : "=a"(c) : "x"(channel) : "p", "y");
      return c == 0x9b ? '\n' : c;
    }

    C:\0\a8\llvm>install\bin\mos-atari8-clang -O2 -Wall -S -fno-lto reload-x.c

    C:\0\a8\llvm>cat reload-x.s
            .text
            .file   "reload-x.c"
            .globl  getchar                         ; -- Begin function getchar
            .type   getchar,@function
    getchar:                                ; @getchar
    ; %bb.0:
            ldx     #0
            stx     840
            stx     841
            ldx     #0
            ;APP
            jsr     58454

            ;NO_APP
            cmp     #155
            bne     .LBB0_2
    ; %bb.1:
            lda     #10
    .LBB0_2:
            ldx     #0
            rts
    .Lfunc_end0:
            .size   getchar, .Lfunc_end0-getchar
                                            ; -- End function
            .ident  "clang version 16.0.0 (https://github.com/llvm-mos/llvm-mos.git 361b5e36af30df63086956b4895445c5eba81065)"
            .section        ".note.GNU-stack","",@progbits
            .addrsig

Now the `ldx #0` is not in the assembly, but emitted by the compiler. The asm instruction promisers not to clobber X. We could have one `ldx #0` instead of three.
