### ISSUE TITLE
Helpful disassembler in case of interest

### ISSUE THREAD

**Issue by rosc77** [llvm-mos/llvm-mos#252]
Hi,

While starting to use llvm-mos, I was very interested to see the asm output... but was never really happy about existing tools.

I wrote my own disassembler, and it can be used to live-monitor while working on code: https://github.com/rosc77/dis64

(Currently, limited to C64 prg. Use it with -m -b to watch a C64 prg file and re-render the asm file on the fly).

Thanks for your great work!
Happy to receive feedback or get contribution!

**Comment by mysterymath** [comment]
Hey rosc77, neat project! I think a Github issue probably isn't the right venue for this, so I'm closing this. You might try posting on the 6502 or c64 forums, or the various retrocomputing Discords (if you haven't already).
