### ISSUE TITLE
Endless loop removed in C++

### ISSUE THREAD

**Issue by pfusik** [llvm-mos/llvm-mos#265]
A trailing endless loop is missing in C++ mode and there is no function epilogue.

    C:\0\a8\llvm>install\bin\mos-atari8-clang++ --version
    clang version 16.0.0 (https://github.com/pfusik/llvm-mos.git efa2448937766fc5a1708416c87ae0f4cd43169b)
    Target: mos
    Thread model: posix
    InstalledDir: C:/0/a8/llvm/install/bin
    Configuration file: C:/0/a8/llvm/install/bin/mos-atari8.cfg

    C:\0\a8\llvm>cat forever.cpp
    #include <stdio.h>

    int main() {
            printf("Hello, world\n");
            for (;;) { }
    }

    C:\0\a8\llvm>install\bin\mos-atari8-clang++ -Os -S -fno-lto -o forever.s forever.cpp

    C:\0\a8\llvm>cat forever.s
            .text
            .zeropage       __rc0
            .zeropage       __rc1
            .zeropage       __rc2
            .zeropage       __rc3
            .zeropage       __rc4
            .zeropage       __rc5
            .zeropage       __rc6
            .zeropage       __rc7
            .zeropage       __rc8
            .zeropage       __rc9
            .zeropage       __rc10
            .zeropage       __rc11
            .zeropage       __rc12
            .zeropage       __rc13
            .zeropage       __rc14
            .zeropage       __rc15
            .zeropage       __rc16
            .zeropage       __rc17
            .zeropage       __rc18
            .zeropage       __rc19
            .zeropage       __rc20
            .zeropage       __rc21
            .zeropage       __rc22
            .zeropage       __rc23
            .zeropage       __rc24
            .zeropage       __rc25
            .zeropage       __rc26
            .zeropage       __rc27
            .zeropage       __rc28
            .zeropage       __rc29
            .zeropage       __rc30
            .zeropage       __rc31
            .file   "forever.cpp"
            .globl  main                            ; -- Begin function main
            .type   main,@function
    main:                                   ; @main
    ; %bb.0:
            ldx     #mos16lo(.Lstr)
            stx     __rc2
            ldx     #mos16hi(.Lstr)
            stx     __rc3
            jsr     puts
    .Lfunc_end0:
            .size   main, .Lfunc_end0-main
                                            ; -- End function
            .type   .Lstr,@object                   ; @str
            .section        .rodata.str1.1,"aMS",@progbits,1
    .Lstr:
            .asciz  "Hello, world"
            .size   .Lstr, 13

            .ident  "clang version 16.0.0 (https://github.com/pfusik/llvm-mos.git efa2448937766fc5a1708416c87ae0f4cd43169b)"
            .section        ".note.GNU-stack","",@progbits
            .addrsig
            ;Declaring this symbol tells the CRT that the stack pointer needs to be initialized.
            .globl  __do_init_stack
            ;Declaring this symbol tells the CRT that the stack pointer needs to be initialized.
            .globl  __do_init_stack

**Comment by mysterymath** [comment]
From http://en.cppreference.com/w/cpp/language/memory_model

In a valid C++ program, every thread eventually does one of the following:

terminate
makes a call to an I/O library function
reads or modifies a volatile object
performs an atomic operation or a synchronization operation
No thread of execution can execute forever without performing any of these observable behaviors.

Note that it means that a program with endless recursion or endless loop (whether implemented as a for-statement or by looping goto or otherwise) has undefined behavior.

**Comment by pfusik** [comment]
https://twitter.com/PR0GRAMMERHUM0R/status/1623366075357270019

![image](https://user-images.githubusercontent.com/351822/217723826-0a2e9e22-1556-4711-8594-6103491ed205.png)
