### ISSUE TITLE
Pessimizing multiplication transformation

### ISSUE THREAD

**Issue by OskarLinde** [llvm-mos/llvm-mos#268]
The compiler tends to transform shift operations into multiplications. This is probably not generally a good idea for the 6502 and results in many-times slower code than with "-O0". For example, the following multiply-by-40 function:

```cpp
__attribute((noinline))
uint16_t mul40_0(uint8_t x) {
    __builtin_assume(x < 25);
    return (x<<3) + (x<<5);
}
```

Results in (using “-Ofast”)

```asm
_Z7mul40_0h:
        ldx     #0
        ldy     #40
        sty     __rc2
        stx     __rc3
        jmp     __mulhi3
```

Instead of the desired (and much faster):
```asm
_Z7mul40_0h:
          asl
          asl
          asl
          tay             
          asl
          sta __rc2  
          lda #0
          rol              
          asl __rc2
          rol              
          tax              
          tya
          adc __rc2
          tay              
          txa
          adc #0
          tax
          tya
          rts
```

There are two aspects to this:
* Disabling the shift->mul transformation is probably always a good idea for 6502 (except maybe for "-Oz")
* It may be a good idea to consider enabling more mul->shift transformations for small/simple constants

**Comment by mysterymath** [comment]
I took a look at this one today; it looks like we wouldn't actually want to interfere with the target-indpendent normalization of the shifts and adds into a single multplication. It's a bit counter-intuitive, but the point of such transformations are more to reduce the number of possible cases for the middle end have to deal with than to optimize. The multiply by 40 and 2 shifts and an add are equivalent, but the multiply is much more amenable to analysis, so it'll have more opportunities to be folded together with other operations.

Accordingly, I think that the right place to deal with this is in the target legalization; it's specific to our target that we prefer shifts to multiplies, and the degree to which that's true varies from target to target. I did find a preexisting target hook in SelectionDAG that's for exactly this: TLI.decomposeMulByConstant. SelectionDAG has cases to recognize multiplications that are sums of powers of two, just like this one, and if the target requests it via that hook, it'll decompose the multiplication back into shifts and adds. This will work regardless of whether the multiply was in the user's code verbatim, generated by an intermediate transform, or was originally a pair of shifts and an add.

It looks like the code hasn't yet been ported from SelectionDAG to GlobalISel. Usually that makes me want to put work on the back burner, but this one seems like it's absolutely worth the effort. I'll try to do this upstream; that way, the other targets experimenting with GlobalISel can also benefit.
