### ISSUE TITLE
Port to Apple M1

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#274]
Probably by triggering some other CI solution

**Comment by johnwbyrd** [comment]
https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/

**Comment by mysterymath** [comment]
It looks like Github Actions cloud support is slated for Q3 of this year: https://github.com/github/roadmap/issues/528
I'd consider buying a dedicated M2 mac mini for this, but if that's accurate, we'd only get 9 months of use out of it, which is a $60/mo TCO. At that, I'm inclined to wait, given the time investment also required to set one of these up. 

If someone has the preexisting hardware, and they're willing to dedicate it to a self-hosted runner, or if a cloud option cheaper than this can be found, feel free. Otherwise, I'll consider this blocked on MacOS M1 github runners. My confidence that MSoft will add this is extremely high, since there's basically no out-of-the-box way to build for current Mac hardware at the moment, which is an existential threat to Github Actions.

**Comment by pfusik** [comment]
What is this ticket about? Making releases of llvm-mos-sdk for Apple silicon?
I have an M1 on my desk.

**Comment by mysterymath** [comment]
Sort-of; we'd want a Github Actions self-hosted-runner on an Apple M1 device somewhere building and testing continuously, and it would probably take up quite a bit of the resources of that device. If we try to do this without continuous builds, then it's likely that that build will end up red by the time it comes to release; which would add unnecessary friction to our release process, given that Github-hosted builders are slated for Q3.

**Comment by johnwbyrd** [comment]
Yeah, such a device would have to be on 24/7 and dedicated solely to llvm-mos CI builds.

**Comment by pfusik** [comment]
I see. I'm not willing to donate my Mac 24/7. :)

I suppose we could cross-compile to Apple silicon on an Intel Mac? But we also want to run the tests?

**Comment by nolemor** [comment]
I just ordered a Mac Mini M1 that I'm up a local runner for Apple M1 builds. While I can't dedicate it 100% to LLVM builds the usage of it will mostly be quite small so it should be possible to us it for llvm-mos builds and testing. 

That said as @pfusik pointed out it would be possible to build the arm64 version on a regular GH runner and only run the tests on the M1 machine.

**Comment by nolemor** [comment]
So I got my M1 mac, but I read this on the setup guide https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security which the TL;DR is that "Don't use on public repos" so yeah, I think I will have to skip this for llvm-mos build :(

**Comment by bcr** [comment]
I think this can be separated into two problems:

1. Building a macOS arm64 target
2. Continuous integration verification for arm64

My understanding is that the GitHub Actions "macos-latest" runner is 12.6.9 running on x86_64, so it by default just builds single-platform x86_64, which is where we're at now.

Part 1 should be possible with any GitHub Action macos runner (including the current one I think) and with just reconfiguring the build. My recommendation would be to do fat binaries through configuration changes in the existing runner, with the caveat that the arm64 variant is untested for now.

I think there should be a suitable arm64 native runner environment now per https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ -- I don't know the budgetary constraints and if the pricing model supports it.

There is also a question of Mac Silicon arm64 diversity -- is it important to test on M1, M2 and M3 or is just M1 sufficient.

It's also possible that running on both `macos-latest` and `macos-latest-xlarge` will automagically get you what you want (the build on the xlarge will yield arm64 binaries.) So it might be just a matrix update.

I made an issue in the SDK repo for this, I didn't look in here first. llvm-mos/llvm-mos-sdk#240

My personal opinion is to fix problem 1 first and characterize the ARM support as "beta" until a CI environment is reliable.

**Comment by bcr** [comment]
> I'll consider this blocked on MacOS M1 github runners

I missed this comment -- I think it's unblocked now @mysterymath

**Comment by bcr** [comment]
On the `cmake` invocation, I think if `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"` is added then fat binaries will be generated, if this direction is interesting. Per [their docs](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) this configuration setting is ignored on other platforms (so it shouldn't disrupt anyone else or require breaking the `macos` build out of the POSIX build.)

https://github.com/llvm-mos/llvm-mos/blob/9b279169a37df896617d6ea05d4bc3c7a6eba1b1/.github/workflows/package.yml#L37-L46

I tested it on my machine on a manual build and it seemed to work fine.

**Comment by bcr** [comment]
Seems to work so far as expected:

```
➜  ~ xattr -d com.apple.quarantine ~/Downloads/llvm-mos-darwin-main.tar.xz 
➜  ~ tar xJf ~/Downloads/llvm-mos-darwin-main.tar.xz                      
➜  ~ llvm-mos/bin/clang --version
clang version 18.0.0 (https://github.com/llvm-mos/llvm-mos 67a958b25e59f7897b33ef725e051e3a3cb94b03)
Target: mos-unknown-unknown
Thread model: posix
InstalledDir: /Users/blake/llvm-mos/bin
➜  ~ file llvm-mos/bin/clang
llvm-mos/bin/clang: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64] [arm64]
llvm-mos/bin/clang (for architecture x86_64):	Mach-O 64-bit executable x86_64
llvm-mos/bin/clang (for architecture arm64):	Mach-O 64-bit executable arm64
➜  ~ 
```

**Comment by mysterymath** [comment]
Awesome, I think we can call this one complete then.
