### ISSUE TITLE
Random text allowed in assembler

### ISSUE THREAD

**Issue by mlund** [llvm-mos/llvm-mos#277]
The following compiles with no complaints. Is it assumed that `something_random` is provided later on? 
~~~ asm
.global myfunc
myfync:
    lda (something_random),y
    rts
~~~

**Comment by mysterymath** [comment]
This is working as intended; in GAS-style assemblers, undefined symbol references are just bare references in the text. This should assemble without issue, but it will fail the eventual link step unless some linked module defines `something_random`.

**Comment by mlund** [comment]
Ahh, thanks. In my case, linkage completed with no errors despite that the symbol was not defined. I realise that I had a `.section code` before the function and removing that and the missing symbol error appears as expected.
