### ISSUE TITLE
Potentially codegen issue with ZP variables

### ISSUE THREAD

**Issue by nolemor** [llvm-mos/llvm-mos#282]
Hi,

I think when using variables in ZP it seems like llvm-mos may generate code that doesn't take advantage of zp loading in some cases. Here is an example where I have modified the `color-cycle.c` example and change the color to this:

```C
__attribute__((section(".zp.bss"))) static char color = 0;
```

```Asm
0000804a <main>:
    804a: a2 00        	ldx	#$0
    804c: ac 02 20     	ldy	$2002
    804f: 10 fb        	bpl	$804c
    8051: a0 08        	ldy	#$8
    8053: 8c 01 20     	sty	$2001
    8056: a9 00        	lda	#$0
    8058: 4c 87 80     	jmp	$8087
   
    805b: ac 02 20     	ldy	$2002
    805e: 10 fb        	bpl	$805b
    8060: e6 03        	inc	$3
    8062: d0 02        	bne	$8066
    8064: e6 02        	inc	$2
    8066: a4 03        	ldy	$3
    8068: e6 02        	inc	$2
    806a: c6 02        	dec	$2
    806c: d0 ed        	bne	$805b
    806e: c0 1e        	cpy	#$1e
    8070: d0 e9        	bne	$805b
    8072: ac 02 20     	ldy	$2002
    8075: a0 3f        	ldy	#$3f
    8077: 8c 06 20     	sty	$2006
    807a: 8d 06 20     	sta	$2006

    807d: ac 20 00     	ldy	$20
    8080: c8           	iny
    8081: ee 20 00     	inc	$20

    8084: 8c 07 20     	sty	$2007
    8087: 86 02        	stx	$2
    8089: 86 03        	stx	$3
    808b: 4c 5b 80     	jmp	$805b
```

What I expect here is that the `ldy` at the bottom should use op-code `$A4` which is load from zeropage, but instead the absolute version is being generated.

Another potential improvement here would be that the compiler can do a `sty` back to memory after the `iny` instead of doing `inc` on the memory location (regardless of zp or not)

**Comment by mysterymath** [comment]
Yes, this definitely appears to be in error. I'll have to spend some time diagnosing this; the `.zp.bss` prefix should be sufficient to cause the assembler to emit zero page addressing and 8-bit relocations, but for some reason it isn't.

**Comment by johnwbyrd** [comment]
Just for the hell of it, have you tried:

`__attribute__((section(".zp"))) static char color = 0;`

**Comment by nolemor** [comment]
@johnwbyrd Interesting. That actually fixes it :thinking: 

```Asm

**Comment by nolemor** [comment]
Also another thing, while perhaps not related to the issue above, if I change the loop counter from `int` to `char` I get this generated code

```Asm
00008034 <main>:
    8034: a9 00        	lda	#$0
    8036: ae 02 20     	ldx	$2002
    8039: 10 fb        	bpl	$8036
    803b: a2 08        	ldx	#$8
    803d: 8e 01 20     	stx	$2001
    8040: a0 00        	ldy	#$0
    8042: ae 02 20     	ldx	$2002
    8045: 10 fb        	bpl	$8042
    8047: 18           	clc
    8048: 69 01        	adc	#$1
    804a: c9 1e        	cmp	#$1e
    804c: d0 f4        	bne	$8042
    804e: ad 02 20     	lda	$2002
    8051: a2 3f        	ldx	#$3f
    8053: 8e 06 20     	stx	$2006
    8056: 8c 06 20     	sty	$2006
    8059: a5 20        	lda	$20
    805b: 18           	clc
    805c: 69 01        	adc	#$1
    805e: e6 20        	inc	$20
    8060: 8d 07 20     	sta	$2007
    8063: a9 00        	lda	#$0
    8065: 4c 42 80     	jmp	$8042
```
Two things to observe there is that the loop counter is now smaller (which makes sense as it's a 8-bit value) but it decides to change the `inc` into `clc / adc` which is a bit unexpected.

**Comment by johnwbyrd** [comment]
This bug can be addressed by rewriting https://github.com/llvm-mos/llvm-mos/blob/86fbb3becc1fb35d16bfb05b95e51a4ecf4b528e/llvm/lib/Target/MOS/MCTargetDesc/MOSAsmBackend.cpp#L278 .  Currently, it only checks to see if the name is contained in the ZeroPageSectionTable, when what we really want to do is check the Name's prefix against the table entries.

**Comment by mysterymath** [comment]
Thanks, that's exactly the deal.

**Comment by mysterymath** [comment]
Closing this with a fix for the original issue, since it's more bug-like than the other tack-on issues.

Please do feel free to file separate issues for those, though; some of these may also be relatively easy to improve, but the work would likely be altogether unlike what was done here.
