### ISSUE TITLE
"cc65 compatibility"

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#29]
Whenever I've brought up feature requests for a new compiler online, the near to first request that comes up is "cc65 compatibility."

On its face, this seems like a sensible request, but the deeper that you think about it, the less sensible this request becomes.  ABI compatibility?  All the #pragma's?  How about all the predefined macros?  Read and write cc65 library files?  Support cl65 linker scripts?

I'd like to break out "cc65 compatibility," which I think is an abstract notion, into a smaller set of specific and measurable features.

**1. ca65 compatibility**.  More specifically, a version of llvm-mc that's capable of emulating ca65, to the point where it can compile and link all the assembly code from the cc65 sdk.  This is not necessarily the same as _complete_ ca65 emulation, whatever that is.  In practice, people could use the cc65 compiler to generate assembly code, and then pass their assembly through llvm-mc and our linker, to receive ELF introspection and real-time debugging and other things that we can do.

**2. ABI compatibility**.  More, specifically, a version of llvm-mos that observes this [https://github.com/cc65/wiki/wiki/Parameter-passing-and-calling-conventions](calling convention).  I'm a bit worried about even making this available, because all comparisons of llvm-mos to cc65 that use such a convention, will cause llvm-mos to look slow and embarrassing.  A great part of llvm-mos's benefits is the control it has over the register allocator, which would all go away if the ABI were compatible.  Thoughts?

**3. clang-cc65 compatibility**.  Considering all the command line flags, #pragmas, and constants that cc65 assumes to exist, and all of which are deviations from ANSI C, I'm going to flat out state that we should not bother.  Honestly, I'd be more tempted to simply give such users a Python script that simply strips all the cc65-specific #pragma's from their source code, converts all the asm commands to clang form, and just give them a header file in the SDK that sets all the cc65-specific constants.  If that.

The end goal, of whatever we call cc65 compatibility, is to get people to leave cc65 alone and to proceed to use a more performant compiler.  To that end, I think we might be able to get ahead of the problem, by publishing a few benchmarks of our own, comparing cc65's performance to llvm-mos.  Interestingly, implementing item 1 above makes it straightforward to try these benchmarks ourselves.

In the pessimal case, our answer to the question of cc65 compatibility is "if it's C99, we can compile it."  In a more optimal case, perhaps I can work on item 1, once some higher priority items are dealt with.

**Comment by johnwbyrd** [comment]
**4. o65 to ELF object file converter.**  We could just skip the whole business, and provide a command line tool to permit cc65 object files to be converted into an ELF compatible format.  The resultant code would not be ABI compatible with llvm-mos, but it would work regardless of how you generated those object files.  Again though, a good bit of pain for not a great deal of long term reward.

**Comment by mysterymath** [comment]
At the end of the day, either ld65 or lld will be making the binary, and the nature of "cc65 compatibility" would depend pretty strongly on which linker they're thinking to use.

If we want ld65 to be able to link code generated with clang/LLVM together with cc65 or ca65 code, then we'd need to be able to produce an object file format that ld65 is capable of ingesting, and we'd need to be able to have our code play nice with the cc65 ABI. Ideally, we'd have a sort of "cloister"; we'd reserve a zero page region for use with the new compiler, and any internal functions would use a better, faster calling convention, be LTOed together, etc. We'd probably want an in-C calling convention annotation to say "make this function here or this call here use the cc65 ABI for its arguments".

For the integration the other way around, we'd need lld to be able to read cc65's object file format and incorporate it into the link. In that case, the cc65 code would be the cloister: we'd reserve temporaries and so forth for it, probably sharing the same stack pointer though. All of the cc65 code would use the same cc65 calling convention; and we'd annotate any LLVM calls to that code with a "cc65 ABI" annotation, causing them to set things up on cc65's soft stack. Similarly, any LLVM functions that need to be called from within the cloister would use the cc65 ABI to get their arguments.

Supporting the cc65 calling convention as a C annotation ([clang::mos_cc65] void foo().... or something) is the common piece between the two, but it's doubtful how useful it would be on its own without linker support. It seems like the LLVM cloister in ld65 would be more useful for folks with existing cc65 projects, so I'd start with that one.

I don't think it's an *enormous* amount of work necessarily, but I doubt it would ever be particularly easy to use. The only way around having to modify the cc65 linker scripts to build the cloister would be to make the cloister as minimal as possible (i.e., basically just the stack pointer and the zero page locations already reserved by cc65), which as you mentioned would produce fairly bad performance.

**Comment by johnwbyrd** [comment]
Thank you for commenting Oliver, your comments are always welcome here and I'm very glad that you're contributing your thoughts and opinions.

I can speak to the assembler portion of things, a bit.  llvm-mos has support for [assembler variants](https://github.com/microsoft/llvm/blob/master/test/TableGen/AsmVariant.td), of which ca65 might theoretically become one.  I recall that the cc65 libraries use the assembler macro functionality in the source code, in a few places, but the library code doesn't exercise all of ca65's features.  So it seems possible to convince llvm-mos to compile ca65 assembly files to ELF,  in the cc65 calling convention, with llvm-mos style relocations.  Then it'd be up to Daniel et al to convince llvm-mos to follow the cc65 calling conventions.

Not a trivial project I think, but possible.

**Comment by mysterymath** [comment]
Closing as won'tfix; issues created along these lines should be more specific.
