### ISSUE TITLE
arithmetic shift treated as 16-bit

### ISSUE THREAD

**Issue by therealkenc** [llvm-mos/llvm-mos#295]
Following pokes the low order jiffy on c64 to top corner of screen as hex:

```
#include <stdint.h>

int main(void) {
    // "0123456789ABCDEF"
    static const uint8_t digits[16] = {
    48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 1, 2, 3, 4, 5, 6
    };
    uint8_t *buf = (uint8_t*)0x400;
    uint8_t n = *(uint8_t*)0xa2;
    buf[0] = digits[n>>4];
    buf[1] = digits[n&0x0f];
    return 0;
}
```

Relevant codegen:

```
main:                                   ; @main
; %bb.0:
	lda	#0
	lsr
	ldx	162
	stx	__rc2
	ror	__rc2
	lsr
	ror	__rc2
	lsr
	ror	__rc2
	lsr
	ror	__rc2
	ldy	__rc2
	lda	main.digits,y
	tay
	sty	1024
	txa
	and	#15
	tay
	lda	main.digits,y
	tay
	sty	1025
	ldx	#0
	txa
	rts
```

I _think_ I know what is going on here. The array index is being treated as a 16-bit value. That lda #0; lsr is going to be zero with no carry every time, but the compiler isn’t aware.

Another interesting thing is the stores into 1024 and 1025 at the end. Those can be lda/sta pairs but the compiler uses x and y as intermediates without needing to.

**Comment by mysterymath** [comment]
No, that issue is due to a there not being any special case handling for
indirecting through zero page pointers; all accesses are done tthrough
imaginary registers. This one is a bit more high level; it's likely just
that constants don't get folded away fully when legalizing wide operations
to 8 bit ones.

**Comment by asiekierka** [comment]
I see. Sorry, then.

**Comment by mysterymath** [comment]
With the recent wide shift optimization, this now lowers to the following. The register allocation is funky, but the thrust of this issue is fixed, so calling this one done.

```
main:                                   ; @main
        lda     162
        sta     __rc2
        lsr     __rc2
        lsr     __rc2
        lsr     __rc2
        lsr     __rc2
        ldx     __rc2
        pha
        lda     main.digits,x
        tax
        pla
        stx     1024
        and     #15
        tax
        lda     main.digits,x
        tax
        stx     1025
        ldx     #0
        txa
        rts
main.digits:
        .ascii  "0123456789\001\002\003\004\005\006"
```
