### ISSUE TITLE
Struct padding of integers

### ISSUE THREAD

**Issue by mlund** [llvm-mos/llvm-mos#322]
`unsigned int` seem to pack differently than `unsigned short` and `uint16_t`. All have a byte count of 2. The below behavior is obtained for all optimization levels.

```c
#include <stdio.h>
#include <stdint.h>

struct data1 {
        unsigned char a;
        unsigned int b;
};

struct data2 {
        unsigned char a;
        unsigned short b;
};

struct data3 {
        uint8_t a;
        uint16_t b;
};

struct __attribute__((__packed__)) data4 {
        uint8_t a;
        uint16_t b;
};


int main(void) {
  printf("SIZEOF DATA1 = %d\n", sizeof(struct data1)); // -> 3
  printf("SIZEOF DATA2 = %d\n", sizeof(struct data2)); // -> 4
  printf("SIZEOF DATA3 = %d\n", sizeof(struct data3)); // -> 4
  printf("SIZEOF DATA4 = %d\n", sizeof(struct data4)); // -> 3
  return 0;
}
```

**Comment by mysterymath** [comment]
Well this was silly; clang hard-codes the alignment of short to 16-bits, and I didn't notice this when initially setting up the target. It should be relatively easy to fix though; just need to add a variable for it and change it in our target. Running through the test suite now to make sure nothing else breaks.
