### ISSUE TITLE
Support for 45GS02 target

### ISSUE THREAD

**Issue by mlund** [llvm-mos/llvm-mos#323]
The 45GS02 cpu is found in the MEGA65 and is derived from CSG4510.

- [ ] Add new target name
- [ ] Mnemonics for working with:
  - [ ] the Q pseudo register, e.g `LDQ`, `STQ`, `CMPQ` etc.
      This involves a new square bracket notation like `LDQ [$nn]`. Described in the [MEGA65 Book](https://github.com/MEGA65/mega65-user-guide).
  - [ ] Mnemonics for flat memory access, i.e. `LDA [$nn],Z` ($EA $B2)
  - Details about the new opcode combinations can be found in the [ACME assembler docs](https://sourceforge.net/p/acme-crossass/code-0/HEAD/tree/trunk/docs/cputypes/cpu%20m65.txt)
- [x] `MAP` opcode
- [ ] Add `all-45gs02-opcodes.s` test file for (dis)assembler
- [ ] Update README
- [ ] Update CPU type for mega65 target

**Comment by asiekierka** [comment]
The 45GS02 actually derives from the CSG4510, which derives from the 65CE02 and is supported by llvm-mos; this takes care of the `MAP` opcode, but not the other extensions.

**Comment by mlund** [comment]
> CSG4510
