### ISSUE TITLE
Predefined macros for CPU type

### ISSUE THREAD

**Issue by rweather** [llvm-mos/llvm-mos#332]
It would be handy to have a predefined macro in the compiler for the CPU type; e.g. `__mosw65c02__` when `-mcpu=mosw65c02` is supplied on the command-line.  This will particularly benefit inline and out of line assembly that can customize its behavior with CPU-specific instructions.  A general "`__mos__`" define for the entire family may also be useful.

**Comment by asiekierka** [comment]
https://github.com/llvm-mos/llvm-mos/pull/310/files#diff-f85f0b556d18b9234898dbc54bb8420bf8206dbb486a0e01fc2e39d4ce5ee307R171-R175 shows how to add the predefined macros `__mos__` and `__ELF__`, matching the platform; adding CPU-specific macros would be a bit more work, however.

**Comment by johnwbyrd** [comment]
The compiler thinks in terms of CPU features, not CPU types.  It may or may not be easier to add macros describing whether the compiler has a specific feature or not.  This is not design advice, merely a remark.

**Comment by rweather** [comment]
Feature-based macros would also be acceptable.

**Comment by tmcintos** [comment]
Presently, I wanted to translate some code written for cc65, which provides alternate sequences for 65C02 vs plain 6502.  It seems like it would be useful to test the instruction set type for such use cases; something fine-grained may be cumbersome.

Also, there is much historical precedent for having per-architecture defines, e.g. from clang on my Apple Silicon Mac:

```
#define __aarch64__ 1
#define __arm64 1
#define __arm64__ 1
```

**Comment by asiekierka** [comment]
> The compiler thinks in terms of CPU features, not CPU types. It may or may not be easier to add macros describing whether the compiler has a specific feature or not. This is not design advice, merely a remark.

It would be *beneficial* to add such macros, but currently the mapping of CPU types to CPU features is only present in the LLVM target logic, and not exposed to Clang. Most Clang targets seem to just repeat themselves in this regard, though...

**Comment by rweather** [comment]
Maybe this can be handled in the SDK's clang.cfg files instead?  e.g. for mos-cx16.cfg:

```
# Clang arguments for the cx16 platform.

# Place directories in include and linker search paths.
-isystem <CFGDIR>/../mos-platform/cx16/include
# -isystem is not passed to the assembler.
-I <CFGDIR>/../mos-platform/cx16/asminc
-L<CFGDIR>/../mos-platform/cx16/lib

# Include target-specific flags.
-mlto-zp=90
-D__CX16__

# Select the CPU type (********NEW*********)
@cpu-mosw65c02.cfg

# Include parent configuration afterwards to give it lesser precedence.
@mos-commodore.cfg
```

New file cpu-mosw65c02.cfg:

```
-mcpu=mosw65c02
-D__mos__
-D__MOS_PHX_PHY
-D__MOS_ZPG_INDIRECT_NO_Y
```

(I have just made up some feature names - I am sure there are better choices).
