### ISSUE TITLE
Inefficient masking of long words?

### ISSUE THREAD

**Issue by onnokort** [llvm-mos/llvm-mos#335]
Hi,

I have the following test code:

```
#include <stdint.h>
#include <stdio.h>

#define VAL 0b00000000000000000111000000000000

uint8_t func1(uint32_t x)
{
    uint8_t *t = (uint8_t*)(&x);
    return (t[1] >> 4)&7;
}

uint8_t func2(uint32_t x)
{
    return (x & VAL) >> 12;
}

int main() {
    volatile uint32_t v, u;
    u=func1(v);
    //u=func2(v);
}
```
If I compile that, I get as the relevant fragment:
```
00000832 <main>:
;     u=func1(v);
     832: a6 22         ldx     $22
;     return (t[1] >> 4)&7;
     834: a9 00         lda     #$0
     836: 4a            lsr
     837: 85 04         sta     $4
;     u=func1(v);
     839: a5 23         lda     $23
;     return (t[1] >> 4)&7;
     83b: 6a            ror
     83c: 46 04         lsr     $4
     83e: 6a            ror
     83f: 46 04         lsr     $4
     841: 6a            ror
     842: 46 04         lsr     $4
;     u=func1(v);
     844: a6 24         ldx     $24
     846: a6 25         ldx     $25
     848: a2 00         ldx     #$0
;     return (t[1] >> 4)&7;
     84a: 6a            ror
     84b: 29 07         and     #$7
;     u=func1(v);
     84d: 85 26         sta     $26
     84f: 86 27         stx     $27
     851: 86 28         stx     $28
     853: 86 29         stx     $29
; }
     855: 8a            txa
     856: 60            rts

```

If I, however, comment `func1` and uncomment `func2` and compile, I get the much longer:

```
00000832 <main>:
;     u=func2(v);
     832: a6 22         ldx     $22
;     return (x & VAL) >> 12;
     834: a9 00         lda     #$0
     836: 4a            lsr
     837: 85 06         sta     $6
;     u=func2(v);
     839: a5 23         lda     $23
     83b: a6 24         ldx     $24
     83d: 86 04         stx     $4
     83f: a6 25         ldx     $25
     841: 86 05         stx     $5
;     return (x & VAL) >> 12;
     843: 66 05         ror     $5
     845: 66 04         ror     $4
     847: 6a            ror
     848: 46 06         lsr     $6
     84a: 66 05         ror     $5
     84c: 66 04         ror     $4
     84e: 6a            ror
     84f: 46 06         lsr     $6
     851: 66 05         ror     $5
     853: 66 04         ror     $4
     855: 6a            ror
     856: 46 06         lsr     $6
     858: 66 05         ror     $5
     85a: 66 04         ror     $4
     85c: 6a            ror
     85d: a2 00         ldx     #$0
;     u=func2(v);
     85f: 29 07         and     #$7
     861: 85 26         sta     $26
     863: 86 27         stx     $27
     865: 86 28         stx     $28
     867: 86 29         stx     $29
; }

```

Unless I made a stupid error, I would expect `func2` to produce the same code as `func1`? (I also don't understand the logic behind the `lsr` statements in the first case?)
(This is compiled using `mos-c64-clang -g -Os` with the current SDK)

**Comment by mysterymath** [comment]
Yep, I think this is just a missing combine in both cases. It fails to notice that only a particular 8 bits of the result are used, so it performs a full-width shift followed by an and of one byte of it. The difference between the two examples is one of language semantics: in the first case, integral promotions have the shift performed at 16 bits, while in the second case, both arguments are already 32-bit, so the shift is performed at 32 bits.

**Comment by onnokort** [comment]
I see, thanks. Am I correct in assuming the string of `ldx`'s in the first case is essentially the same problem as well?
In my use case, I have a lot of odd but narrow slices of 32bit values and I took this guide from your wiki:

` It's often fine to compute values in wide types, so long as you only use part of the result. The compiler is usually pretty good at trimming down the computation.`

[Thank you for your great backend, btw!]

**Comment by mysterymath** [comment]
> I see, thanks. Am I correct in assuming the string of `ldx`'s in the first case is essentially the same problem as well? In my use case, I have a lot of odd but narrow slices of 32bit values and I took this guide from your wiki:

Ah, I didn't notice this; it's actually because the load of v is volatile, and the backend takes this to mean that a full-width read of v must occur, even if the value is unused. This makes a difference in case of e.g. MMIO registers that are triggered on read.

**Comment by mysterymath** [comment]
This is mostly for my own notes. There's two things at play here. First, the global instruction selector is young; it doesn't yet have the demanded bits analysis and optimization that SelectionDAG has. We really want that; we only want to compute bytes that are actually demanded. There's also no constant folding on the custom 6502 generic opcodes, in this case, G_LSHRE (even logical shift right, modelling both LSR and ROR). With a demanded bits analysis and constant folding, both examples would fold all the way down to 4 LSRs of a single byte, then a return (even the AND should disappear). 

We got a lot of this for free with just the existing known bits analysis and dead code elimination, but it would pay for us to build out some demanded bits infrastucture ahead of GISel upstream.

**Comment by mysterymath** [comment]
I've added constant folding for the 6502-specific generic machine instructions; that gets us part of the way there. With this we have:

`func1`
```
main:                                   ; @main
; %bb.0:
	ldx	mos8(.Lmain_zp_stk)
	lda	mos8(.Lmain_zp_stk+1)
	ldx	mos8(.Lmain_zp_stk+2)
	ldx	mos8(.Lmain_zp_stk+3)
	lsr
	lsr
	lsr
	lsr
	and	#7
	sta	mos8(.Lmain_zp_stk+4)
	ldx	#0
	stx	mos8(.Lmain_zp_stk+5)
	stx	mos8(.Lmain_zp_stk+6)
	stx	mos8(.Lmain_zp_stk+7)
	txa
	rts
```

`func2`
```
main:                                   ; @main
; %bb.0:
	ldx	mos8(.Lmain_zp_stk)
	lda	mos8(.Lmain_zp_stk+1)
	ldx	mos8(.Lmain_zp_stk+2)
	stx	__rc2
	ldx	mos8(.Lmain_zp_stk+3)
	stx	__rc3
	lsr	__rc3
	ror	__rc2
	ror
	lsr	__rc3
	ror	__rc2
	ror
	lsr	__rc3
	ror	__rc2
	ror
	lsr	__rc3
	ror	__rc2
	ror
	and	#7
	sta	mos8(.Lmain_zp_stk+4)
	ldx	#0
	stx	mos8(.Lmain_zp_stk+5)
	stx	mos8(.Lmain_zp_stk+6)
	stx	mos8(.Lmain_zp_stk+7)
	txa
	rts
```

**Comment by mysterymath** [comment]
I've added a known bits analysis for shifts, ands, and ors. With that, func2 collapses down to:
```
main:                                   ; @main
; %bb.0:                                ; %entry
        ldx     .Lmain_sstk
        lda     .Lmain_sstk+1
        ldx     .Lmain_sstk+2
        ldx     .Lmain_sstk+3
        lsr
        lsr
        lsr
        lsr
        and     #7
        sta     .Lmain_sstk+4
        stz     .Lmain_sstk+5
        stz     .Lmain_sstk+6
        stz     .Lmain_sstk+7
        ldx     #0
        txa
        rts
```

This also gets us a one second win on 10 iterations of CoreMark, which is best benchmark we have. Thanks for the bug report!

**Comment by onnokort** [comment]
You are welcome - rather: thanks for the backend! :) I have built 3161ec4cdb44952c1790d3f6243ecc3ff82dcf6e and that reduced the time for the C64 to boot Linux by about so 4.2% @ `-O3` with LTO etc., which is nice. However, I haven't checked whether it was this or another improvement compared to the latest SDK release.

**Comment by mysterymath** [comment]
> You are welcome - rather: thanks for the backend! :) I have built [3161ec4](https://github.com/llvm-mos/llvm-mos/commit/3161ec4cdb44952c1790d3f6243ecc3ff82dcf6e) and that reduced the time for the C64 to boot Linux by about 4.2% @ `-O3` with LTO etc., which is nice. However, I haven't checked whether it was this or another improvement compared to the latest SDK release.

Oh my God you absolute madman. That's amazing!
