### ISSUE TITLE
llvm-objdump -d --symbolize-operands should show symbolic destination address in disassembly, but doesn't

### ISSUE THREAD

**Issue by tmcintos** [llvm-mos/llvm-mos#336]
Given:

```
0000ec7e <memcpy>:
    ec7e: 85 08        	sta	$8
...
```

I expected something like:

    df8b: 20 7e ec     	jsr	memcpy

But the actual result is:

    df8b: 20 7e ec     	jsr	$ec7e

This usage of absolute addresses makes reading disassembly pretty tedious.

Am I missing some option that controls this?

**Comment by tmcintos** [comment]
Similarly for instructions accessing variables in memory, I would expect these references to be symbolic with this option, but I only see absolute addresses.

**Comment by johnwbyrd** [comment]
See also https://reviews.llvm.org/rGb66328701a525d026a91b10df011712e5811319e for an example of adding this functionality.

**Comment by tmcintos** [comment]
Sweet, thanks for the quick fix!
