### ISSUE TITLE
Compiler crash on godbolt

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#337]
Replication case is visible at: https://godbolt.org/z/rzxe1Gjef

Doesn't seem to crash if -Os is replaced with -O2.

**Comment by johnwbyrd** [comment]
Something about the struct Ball ball[10]; line.  Replacing that with struct Ball *ball; causes it not to crash.

**Comment by mysterymath** [comment]
Somehow we ended up w "experimental assignment tracking" for debug info, and Globalisel doesn't support it. Still gotta figure out how that happened though.

**Comment by cogwheel** [comment]
I'm having the same problem trying to write a printf-like: https://godbolt.org/z/hMEhvxefv

Removing `-O1` causes it to succeed, but obv with very poor code quality.

**Comment by johnwbyrd** [comment]
Thank you Daniel.
