### ISSUE TITLE
Propagate --num-imag-ptr choices to object files

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#34]
If different sources are compiled with different --num-imag-ptr settings, comedy will ensue.

The linker ought to be able to verify that the number of imaginary pointers is the same for all objects being linked, and it should refuse to run, with a detailed explanation, if this is not so.

**Comment by johnwbyrd** [comment]
Maybe a severe linker warning will be enough.  There may be some scenarios where it's ok to mix different --num-imag-ptr settings, but at least the user needs to know that the code PROBABLY will not run.

**Comment by mysterymath** [comment]
We probably shouldn't allow people to mix num-imag-ptr settings for now. If interrupt code is ever going to work well, we'll probably need a compiler annotations for marking functions with num-imag-ptr. This would make it fairly easy to carve out the interrupt handler routines in C itself. We'd also be able to emit compiler errors whenever a function with a lower num-imag-ptr directly calls a function with a higher num-imag-ptr.
