### ISSUE TITLE
Establish -fshort-enums behavior in ABI

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#341]
The 6502 should default to using byte-sized enums whenever this is possible, i.e., the behavior of `-fshort-enums`. This represents an ABI-breaking change, but it should allow more code to be 8-bit, which is a fairly unambiguous win. It may create some portability issues with libraries that expect other conventions, but such code seems also likely to assume 32-bit int and similar.

**Comment by johnwbyrd** [comment]
Probably, but this behavior needs to be well documented and overridable, as we can imagine that this assumption will obscurely break some existing code.

**Comment by mysterymath** [comment]
Definitely needs to be well-documented; that's actually required by the standard, as it's an implementation-defined behavior. IIUC, passing -fno-short-enum will produce the other behavior, but it wouldn't compile against code that is written with a different convention. We still do need to pick one to avoid an ABI split, and `-fshort-enum` seems like the right pick on merit.

**Comment by asiekierka** [comment]
I'm not 100% sure this is the right approach, given that C23 and modern C++ allow defining the type of an enum. However, it intuitively seems like a good idea given the 6502's limitations and how enums are most commonly used.

**Comment by johnwbyrd** [comment]
Ergo, I suggest putting -fshort-enums into the cmake options in llvm-mos-sdk, as opposed to burning the option into the compiler build.

**Comment by mysterymath** [comment]
We have to burn something into the compiler; right now that's `-fno-short-enums`, which just doesn't make a whole lot of sense on an 8-bit target. This is a specific callout that the standard gives to allow efficient compilation to space-constraints targets or those where access to values smaller than int is cheap; we are both.

**Comment by johnwbyrd** [comment]
Theoretically, if you provided one option via a command line and another present internally in the compiler, would the one on the command line overrule?

**Comment by johnwbyrd** [comment]
https://interrupt.memfault.com/blog/best-and-worst-gcc-clang-compiler-flags#-fshort-enum

**Comment by mysterymath** [comment]
> Theoretically, if you provided one option via a command line and another present internally in the compiler, would the one on the command line overrule?

All targets appear to do in the Clang driver is set the default behavior of the flag if not specified on the command line. If specified, the last specification wins, as per usual.

> https://interrupt.memfault.com/blog/best-and-worst-gcc-clang-compiler-flags#-fshort-enum

There appear to be two arguments here:
  - Value additions to an enum can break ABI with `-fshort-enums`
  - Performing operations on types narrower than `int` is slow.
 
The second concern doesn't apply, and the first barely does; maintaining ABI stability is dramatically less important for us than a typical target, and it only breaks when going from a char-sized enum to an int-sized enum, which isn't a common occurrence.

**Comment by johnwbyrd** [comment]
So long as the choice can be overridden by the user, I'm on board with the change.

**Comment by mysterymath** [comment]
Reverted a0e020a; this caused an end-to-end test failure in enum-3.c
