### ISSUE TITLE
ELF specification/implementation disagreement on relocation types

### ISSUE THREAD

**Issue by asiekierka** [llvm-mos/llvm-mos#358]
LLVM `MOS.def`:

```
// The low byte from the segment value in a 24-bit address.
ELF_RELOC(R_MOS_ADDR24_SEGMENT_LO,     10)

// The high byte from the segment value in a 24-bit address.
ELF_RELOC(R_MOS_ADDR24_SEGMENT_HI,     11)

// A 16-bit PC-relative jump value.  Used for the BRL instruction.
ELF_RELOC(R_MOS_PCREL_16,              12)

// Relocations for DWARF.
ELF_RELOC(R_MOS_FK_DATA_4,             13)
ELF_RELOC(R_MOS_FK_DATA_8,             14)

// Decimal ASCII address encoding.
ELF_RELOC(R_MOS_ADDR_ASCIZ,            15)

// A 16-bit immediate value.
ELF_RELOC(R_MOS_IMM16,                 16)
```

Wiki:

```
R_MOS_ADDR24_SEGMENT_LO | 10 | The low byte from the segment value in a 24-bit address.
-- | -- | --
R_MOS_ADDR24_SEGMENT_HI | 11 | The high byte from the segment value in a 24-bit address.
R_MOS_FK_DATA_4 | 12 | A generic four-byte, 32-bit value.  Although MOS does not use native  32-bit relocations, DWARF may use this relocation type when describing  debug information.
R_MOS_FK_DATA_8 | 13 | A generic eight-byte, 64-bit value.  Although MOS does not use  native 64-bit relocations, DWARF may use this relocation type when  describing debug information.
R_MOS_ADDR_ASCIZ | 14 | A null-terminated, decimal ASCII string of the value.  Generated by .mos_addr_asciz assember directive.  See Assembler for details.
R_MOS_IMM16 | 15 | A 16-bit immediate value.
```

At [some point in time](https://github.com/llvm-mos/llvm-mos/pull/147), `R_MOS_PCREL_16` was added to the code while not being included in the official specification; this led to an unnoticed disagreement between the numbering in the specification and in the implementation.

One of these has to be corrected to match the other; personally, given that I'm not aware of any third-party implementations of the ELF standard as used by LLVM-MOS, I'd guess that a breaking change to the specification may be more preferable.

**Comment by johnwbyrd** [comment]
The specification should follow the code, ideally simultaneously, but sometimes we have dropped that particular ball.

**Comment by rweather** [comment]
The elf2o65 tool in [o65utils](https://github.com/rweather/o65utils) is a third-party implementation of the ELF standard as used by LLVM-MOS.  I have updated o65utils to match the LLVM-MOS code rather than the wiki.

R_MOS_PCREL_16 and higher are unlikely to appear in the ELF executables that elf2o65 can convert, so there should be no breakage on my end with either the old or new numbers.

I agree that the wiki should be updated - the code change is >1.5 years old - old enough to be the de facto standard.

**Comment by asiekierka** [comment]
In that case, I am updating the wiki (specification version 0.3.0) to fix this and add the new SPC700 flags.
