### ISSUE TITLE
G_PTR_ADD can create G_CONSTANT with no assigned register bank

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#38]
In some cases, the MOSCombiner pass may create a new virtual register and assign a G_CONSTANT to it.   This will happen if, during the MOSCombiner step, the CombinerHelper::matchPtrAddImmedChain and CombinerHelper::applyPtrAddImmedChain functions get called.

However, the MOSCombiner pass happens after register bank selection.  Ergo, because of the newly created virtual register not being assigned to any bank, MOSCombiner will fail verification after this pass, and abort.

Several workarounds are possible.  We could recreate the MOSCombinerHelper and special case these functions.  We could run a "mini" register bank selection pass ourselves, after MOSCombiner, which should be easy since we have one bank.

All this happens before the MOSInstructionSelector, so changes there won't help.

Before MOSCombiner pass:

bb.1.entry:
  liveins: $a, $x, $y, $rc6, $rs1
  %0:any(p0) = COPY $rs1
  %3:any(s8) = COPY $a
  %4:any(s8) = COPY $x
  %5:any(s8) = COPY $y
  %6:any(s8) = COPY $rc6
  G_STORE %3:any(s8), %0:any(p0) :: (store 1 into %ir.x11, !tbaa !2)
  %13:any(s8) = G_CONSTANT i8 1
  %17:any(p0) = G_PTR_ADD %0:any, %13:any(s8)
  G_STORE %4:any(s8), %17:any(p0) :: (store 1 into %ir.x11 + 1, !tbaa !2)
  %14:any(s8) = G_CONSTANT i8 2
  %8:any(p0) = G_PTR_ADD %0:any, %14:any(s8)
  G_STORE %5:any(s8), %8:any(p0) :: (store 1 into %ir.y2, !tbaa !7)
  %11:any(p0) = G_PTR_ADD %8:any, %13:any(s8)
  G_STORE %6:any(s8), %11:any(p0) :: (store 1 into %ir.y2 + 1, !tbaa !7)
  RTS

After:

bb.1.entry:
  liveins: $a, $x, $y, $rc6, $rs1
  %0:any(p0) = COPY $rs1
  %3:any(s8) = COPY $a
  %4:any(s8) = COPY $x
  %5:any(s8) = COPY $y
  %6:any(s8) = COPY $rc6
  G_STORE %3:any(s8), %0:any(p0) :: (store 1 into %ir.x11, !tbaa !2)
  %13:any(s8) = G_CONSTANT i8 1
  %17:any(p0) = G_PTR_ADD %0:any, %13:any(s8)
  G_STORE %4:any(s8), %17:any(p0) :: (store 1 into %ir.x11 + 1, !tbaa !2)
  %14:any(s8) = G_CONSTANT i8 2
  %8:any(p0) = G_PTR_ADD %0:any, %14:any(s8)
  G_STORE %5:any(s8), %8:any(p0) :: (store 1 into %ir.y2, !tbaa !7)
  **%19: _ (s8) = G_CONSTANT i8 3
  %11:any(p0) = G_PTR_ADD %0:any, %19 : _ (s8)**
  G_STORE %6:any(s8), %11:any(p0) :: (store 1 into %ir.y2 + 1, !tbaa !7)
  RTS

**Comment by mysterymath** [comment]
Ahh, good catch!

From the looks of the implementations in CombinerHelper.cpp, it doesn't look like the GlobalISel  combiners are register bank aware at all. It looks like AArch64 runs its combiner pass right before register bank selection, but I put ours right before instruction selection. This was a flat-out mistake from the looks of it. Should be trivial to fix: since our reg-bank-select doesn't really do anything except satisfy the verifier, we can just move the second MOSCombine instantiation MOSTargetMachine.cpp from addPreGlobalInstructionSelect() to addPreRegBankSelect().

**Comment by johnwbyrd** [comment]
a2d7961 should fix.
