### ISSUE TITLE
No error message for overlapping clobbers and input registers

### ISSUE THREAD

**Issue by juj** [llvm-mos/llvm-mos#385]
Consider the following implementation of a C64 KERNAL ROM `SAVE` function:

```cpp
#include <stdint.h>

#define _HI(x) ((uint8_t)(((uint16_t)(x))>>8))
#define _LO(x) ((uint8_t)(uint16_t)(x))

uint8_t _SAVE(const void *start, const void *end)
{
  uint8_t error;
  // JSR $FFD8: KERNAL ROM 'SAVE' routine
  // Writes a contiguous region of bytes from memory at [start, end[ to disk.
  // Inputs:
  //   A: a pointer to a 16-bit variable in the zero-page memory address that contains the value of 'start'
  //   X: low 8 bits of 'end' address
  //   Y: high 8 bits of 'end' address
  // Outputs:
  //   C: If 1, error occurred. If 0, no error.
  //   A: Error code.
  // Clobbers: X, Y
  __asm__ volatile(
    "LDA #%[zp]\n"
    "JSR $FFD8\n" // Call the 'SAVE' KERNAL ROM routine
    :"=a"(error)  // asm outputs
    :[zp]"r"(start),"x"(_LO(end)),"y"(_HI(end)) // asm inputs
    :"c" // asm clobbers (*BUG*)
  );
  return error;
}
```

This code looks nice and lean, and it generates the following tight asm:

```asm
_SAVE(void const*, void const*):                         ; @_SAVE(void const*, void const*)
        ldx     __rc4
        ldy     __rc5
        lda     #__rc2
        jsr     65496
        rts
```
https://godbolt.org/z/WY3vfWvrK

which was an absolute delight to see.

However, it has a subtle programming error in it. The [C64 KERNAL ROM SAVE function](https://www.pagetable.com/c64ref/kernal/#SAVE) `JSR $FFD8` is documented to not preserve the values of `X` and `Y` registers as part of its computation:

![image](https://github.com/llvm-mos/llvm-mos/assets/225351/2f6a45a0-bf98-4531-b811-77999d7bf358)

This means that after `jsr     65496` above returns, `x` and `y` no longer contain values from `__rc4` and `__rc5` respectively, and if the compiler might be assuming `x` and `y` to be live across this inline asm block, then it would produce incorrect code. (This could happen if `_SAVE` is inlined to caller, as probably makes sense, since the implementation is so short)

No biggie, this situation can be fixed by declaring both `"x"` and `"y"` to the asm statement clobber list, changing the line

```
    :"c" // asm clobbers (*BUG*)
```
above to
```
    :"c","x","y"
```
to tell the compiler that the inputs `x` and `y` will be destroyed as part of exiting the inline asm statement, so cannot be treated live across the inline asm call.

However, by doing that, something odd happens, and the generated assembly becomes just

```asm
_SAVE(void const*, void const*):                         ; @_SAVE(void const*, void const*)
        lda     #__rc2
        jsr     65496
        rts
```
That is, the compiler dropped setting up both input statements
```
        ldx     __rc4
        ldy     __rc5
```
for the inline asm block altogether.

See https://godbolt.org/z/vnYco7r1a

That does not seem to be correct? To my understanding, declaring an asm block that receives an input that is *destroyed* (vs declaring an input that is *preserved* after the block), would be done with this kind of marking of the register as input, and then adding that register to the clobber list as well?

But for some reason the compiler seems to think that an input that is clobbered would be something that does not need to be passed into the inline asm block at all?

**Comment by mysterymath** [comment]
From the GCC manual: "Clobber descriptions may not in any way overlap with input or output arguments." This is undefined behavior.

**Comment by juj** [comment]
Thanks, I had completely missed that!

Do you know what is the mechanism for declaring preserved vs destroyed inputs in inline asm?

**Comment by juj** [comment]
Ah, it looks like such destroyed inputs should then be just marked as an output?

From https://gcc.gnu.org/onlinedocs/gcc-3.3.1/gcc/Extended-Asm.html :

"There is no way for you to specify that an input operand is modified without also specifying it as an output operand."

So the correct fix to the original programming error illustrated, would be to write the following inline asm?

```c++
uint8_t _SAVE(const void *start, const void *end)
{
  uint8_t error;
  uint8_t dummy, dummy2;
  __asm__ volatile(
    "LDA #%[zp]\n"
    "JSR $FFD8\n"
    :"=a"(error), "=x"(dummy), "=y"(dummy2)
    :[zp]"r"(start),"x"(_LO(end)),"y"(_HI(end))
    :"c"
  );
  return error;
}
```
(I find that I needed to add dummy outputs, or otherwise that wouldn't compile. The syntax is quite awkward though.

With respect to `"Clobber descriptions may not in any way overlap with input or output arguments."`, it is sad to see how the inline asm statement is stuck in the 90s: the compiler could easily diagnose with a string list intersection search to figure out if any input or output register is actually specified in a clobber, and then outright emit a compilation error. But for some reason that is presented as a silent "nope, you shall silently get UB if you do that." Yikes :(

**Comment by juj** [comment]
Re-reading, I find that I had googled an ancient GCC 3.3.1 URL above to read the docs.

Checking the latest docs at https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html , it says

```
Warning: Do not modify the contents of input-only operands (except for inputs tied to outputs).
The compiler assumes that on exit from the asm statement these operands contain the same values
as they had before executing the statement. It is not possible to use clobbers to inform the
compiler that the values in these inputs are changing. One common work-around is to tie the changing
input variable to an output variable that never gets used.
```
Reads like someone else made the mistake that I did, and they added that paragraph in the docs exactly for that.

Wish they would have just fixed the meaning of the clobber statement... 🙄

 In any case, the above documentation verifies that `"=x"(dummy), "=y"(dummy2)` should be the way that this should be used.

**Comment by juj** [comment]
> With respect to `"Clobber descriptions may not in any way overlap with input or output arguments."`, it is sad to see how the inline asm statement is stuck in the 90s: the compiler could easily diagnose with a string list intersection search to figure out if any input or output register is actually specified in a clobber, and then outright emit a compilation error.

Oh wait, upon further testing, I realize that Clang does diagnose when targeting x86 native assembly when this situation occurs, so this is does not seem to be a "result of old gcc syntax" situation:

```c++
int Double(int x)
{
    int ret;
    __asm__(
        "addl %%ecx, %%ecx\n"
        "movl %%ecx, %%ebx"
    :"=b"(ret)
    :"c"(x)
    :"ecx"
    );
    return ret;
}
```
gives a nice
```
error: asm-specifier for input or output variable conflicts with asm clobber list
```

x86-64 clang 17.0.1: https://godbolt.org/z/Mr5cM5MrG

x86-64 gcc 13.2 says

```
error: 'asm' operand has impossible constraints
```
https://godbolt.org/z/fMMn95qaK
```

So I wonder if it might be an llvm-mos specific behavior that overlapping inputs/outputs with clobbers are not detected? And that feature just didn't come automatically from general LLVM codebase?

> From the GCC manual: "Clobber descriptions may not in any way overlap with input or output arguments." This is undefined behavior.

It is now clear that clobbers may not overlap with inputs or outputs, and I re-read the doc page https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html about this. I don't see where it would make the conclusion that doing so would result in undefined behavior.

I wonder if it would make sense to reopen this to improve llvm-mos handling of inline asm blocks to produce the same error diagnostic as Clang and GCC do? (naturally not a big priority since my code works now 😃 though seems like there is an angle to improve here)
