### ISSUE TITLE
Applying __attribute__((leaf)) to __asm__ breaks program in -Os or -Oz, but works in -O0, -O1, -O2 and -O3

### ISSUE THREAD

**Issue by juj** [llvm-mos/llvm-mos#392]
Over on the Discord server, I recall @mysterymath recommending to gratuitously use `__attribute__((leaf))` to improve optimizer performance around inline asm blocks.

In the following program, the `__attribute__((leaf))` directives on the asm statements result in the program working incorrectly.

To my understanding these usages should be safe in this specific context, but for some reason they aren't. Here's the program:

```c++
#include <stdint.h>

void _CHROUT(uint8_t byte) // Print character to screen
{
  __attribute__((leaf)) // Unexpected: comment out this line unbreaks program
  __asm__ volatile("JSR $FFD2"::"a"(byte):"c");
}

void chrout_u16(uint16_t num) // Print uint16 to screen as decimal
{
  uint8_t zp0, zp1, zp2;
  __attribute__((leaf)) // Alternatively commenting out this line also seems to unbreak program
  __asm__(R"(
    SED // Enter Binary Coded Decimal (BCD) mode (affects ADC commands below)

    LDA #0
    STA %[zp0] // zp0-zp2 will store the output BCD digits, 0-65535.
    STA %[zp1] // Initialize these all to zero to start
    STA %[zp2]

    LDX #16 // Loop each of the 16 bits of the u16 input
loop%=:
    ROL %[input]   // Shift the input u16 one bit to the left
    ROL %[input]+1 // rotating the next MSB bit of input into Carry

    LDA %[zp0] // Multiply the three BCD number pairs by two, and add the input bit from carry to the BCD
    ADC %[zp0]
    STA %[zp0]
    LDA %[zp1]
    ADC %[zp1]
    STA %[zp1]
    LDA %[zp2]
    ADC %[zp2]
    STA %[zp2]

    DEX     // Loop back to next input bit
    BNE loop%=

    CLD // Exit BCD mode
  )":[zp0]"=r"(zp0), [zp1]"=r"(zp1), [zp2]"=r"(zp2), [input]"+r"(num)::"a","x","c");

  if (zp2)     goto five;
  if (zp1 > 9) goto four;
  if (zp1)     goto three;
  if (zp0 > 9) goto two;
  goto one;
five:  _CHROUT('0'+ zp2);
four:  _CHROUT('0'+(zp1>>4));
three: _CHROUT('0'+(zp1&0xF));
two:   _CHROUT('0'+(zp0>>4));
one:   _CHROUT('0'+(zp0&0xF));
}

int main()
{
  chrout_u16(65535);
}
```
Building with `mos-c64-clang++ a.cpp -o a.prg -O3` works (and also `-O0`, `-O1` and `-O2` work).

Oddly, changing optimization to `-Os` or `-Oz` results in the program breaking.

I wonder if I have incorrectly applied `__attribute__((leaf))` in this case, or might this be a bug of some sort?

**Comment by mysterymath** [comment]
Can you do any sleuthing to find out what's wrong in the generated assembly?

**Comment by juj** [comment]
> What is the observed behavior, and what is the expected behavior?

Sorry, missed writing that.

The program is expected to print out `65535` in console.

In -O0 - -O3 the program does so, but in `-Oz` the program instead prints nothing.

---------------

A shorter test case that instead converts and prints number `99` only. That exhibits the same bug:

```c++
#include <stdint.h>

void _CHROUT(uint8_t byte) // Print character to screen
{
  __attribute__((leaf)) // Unexpected: comment out this line unbreaks program
  __asm__ volatile("JSR $FFD2"::"a"(byte):"c");
}

void chrout_u16(uint16_t num) // Print uint16 to screen as decimal
{
  uint8_t zp0;
  __attribute__((leaf)) // Alternatively commenting out this line also seems to unbreak program
  __asm__(R"(
    SED // Enter Binary Coded Decimal (BCD) mode (affects ADC commands below)

    LDA #0
    STA %[zp0] // zp0-zp2 will store the output BCD digits, 0-65535.

    LDX #16 // Loop each of the 16 bits of the u16 input
loop%=:
    ROL %[input]   // Shift the input u16 one bit to the left
    ROL %[input]+1 // rotating the next MSB bit of input into Carry

    LDA %[zp0] // Multiply the three BCD number pairs by two, and add the input bit from carry to the BCD
    ADC %[zp0]
    STA %[zp0]

    DEX     // Loop back to next input bit
    BNE loop%=

    CLD // Exit BCD mode
  )":[zp0]"=r"(zp0), [input]"+r"(num)::"a","x","c");

  if (zp0 > 9) _CHROUT('0'+(zp0>>4));
  _CHROUT('0'+(zp0&0xF));
}

int main()
{
  chrout_u16(99);
}
```
`-Os` and `-Oz` print nothing, but `-O1` - `-O3` print out correctly.

**Comment by juj** [comment]
Very peculiar: whereas `-O3` works, `-O3 -fno-inline-functions` does not, and also breaks just like `-Os` and `-Oz` does. (I was trying to use `-fno-inline-functions` to maybe be able to see better in Godbolt what the difference between `-Oz` and `-O3` would be).

Also `-O1 -fno-inline-functions` breaks as well.

**Comment by juj** [comment]
In the breaking case, the compiler replaces the whole of `main` with just

```
main:                                   ; @main
        ldx     #0
        txa
        rts
```
i.e. somehow thinking that it wouldn't need to call the `chrouot_u16` function at all.

**Comment by juj** [comment]
Maybe smallest repro is

```c++
void chrout_u16()
{
  __attribute__((leaf)) asm volatile(R"(
    LDA #$42
    JSR $FFD2
  )":::"a","c");
}

int main()
{
  chrout_u16();
}
```
which works with `-O1`, but breaks with `-O1 -fno-inline-functions`. Not completely sure if this repro is reducing away some meaning of the original code, since it looks like this repro case no longer fails with just `-Os` or `-Oz`, but `-fno-inline-functions` is needed.

**Comment by mysterymath** [comment]
Yep, this appears to be a real bug, likely to do with how we implemented leaf. It's causing `mayHaveSideEffects()` to return false on the call to `chrout_u16` which causes it to be stripped out.
