### ISSUE TITLE
Incorrect codegen somewhere around inline assembly

### ISSUE THREAD

**Issue by juj** [llvm-mos/llvm-mos#393]
As a caution to avoid #392, I removed all `__attribute__((leaf))` parts from my codebase.

In the reduced test case in #392, it fixed the issue. However, I was surprised to notice that it did not fix my full codebase however.

I reduced the codebase again, and this time got down to the following code.

```c++
#include <stdint.h>
#include <stdarg.h>

uint8_t __stack_avail()
{
  uint8_t stack_pointer;
  __asm__("TSX":"=x"(stack_pointer)::);
  return stack_pointer;
}

void _assert(bool condition)
{
  while(!condition) __asm__("NOP":::"memory"); // Intentional lock up if condition is false (doesn't occur in this test case)
}

void _CHROUT(uint8_t byte)
{
  _assert(__stack_avail() > 8); // This assert doesn't hit, but can't reduce it either, or bug vanishes
  __asm__ volatile("JSR $FFD2"::"a"(byte):"c"); // Tried to add A, X and Y to clobbers here in case $FFD2 might destroy more, but no effect
}

void chrout_u16(uint8_t num)
{
  uint8_t zp0;
  __asm__(R"(
    LDA %[input]
    STA %[zp0]
  )":[zp0]"=r"(zp0), [input]"+r"(num)::"a");
  _CHROUT('0'+zp0);
}

void Printf(const char *format, ...)
{
  va_list args;
  va_start(args, format);
  int dst;

  for(; *format; ++format)
  {
    switch(*format)
    {
    case 'd':
      dst = va_arg(args, int);
      if (dst < 0) { _CHROUT('-'); dst = -dst; }
      chrout_u16(dst);
    break;
    case 'u':
      dst = va_arg(args, unsigned int);
      chrout_u16(dst);
    break;
    }
  }
  va_end(args);
}

int main()
{
  Printf("%u", 9);
}
```

Building with `-Os`, `-O1`, `-O2`, `-O3`, or `-Os` prints out the correct expected result: `9`.

However building with `-Oz` prints out `0` instead.

Unlike #392, this issue does not seem to be perturbed by `-fno-inline-functions`. E.g. building with `-O3 -fno-inline-functions` still works.

Oddly, I am struggling to reduce the test case further. Tried getting rid of varargs, __stack_avail(), or the assert(), which all would also reduce the bug away. Tried also removing the unused `case 'd':` from the switch-case, but surprisingly that had the effect of hiding the bug as well.

This does seem like might be something different than #382, or then maybe I did something wrong in my asm clobbers - although I've been double and triple checking them to try to find a mistake.

**Comment by juj** [comment]
Reading the disassembly at https://godbolt.org/z/rc3eoGaG9 , the generated code for `__stack_avail`, `_assert`, `_CHROUT` and `chrout_u16` all look good to me. I suspect this would be something to do with varargs handling.

**Comment by juj** [comment]
Super random, but adding `__asm__("NOP":::"memory");` statement right after _either_ call to `chrout_u16` make the bug vanish. E.g.

```c++
    ...
    switch(*format)
    {
    case 'd':
      dst = va_arg(args, int);
      if (dst < 0) { _CHROUT('-'); dst = -dst; }
      chrout_u16(dst);
      __asm__("NOP":::"memory"); // added this
    break;
    case 'u':
      dst = va_arg(args, unsigned int);
      chrout_u16(dst);
    break;
    }
    ...
```

does not have the issue. (Again really odd since the case 'd' is not even reached).

Alternatively, adding that `__asm__("NOP":::"memory");` right after the second `chrout_u16(dst);` in `case 'u':` also removes the bug.

But adding `__asm__("NOP":::"memory");` at the end inside of `chrout_u16(dst);` function implementation itself does not fix the issue.

Not sure if all that is a red herring or what. Diffing what the compiler codegens differently when that NOP is added, I see this:

![image](https://github.com/llvm-mos/llvm-mos/assets/225351/70788157-77d1-4659-af33-b42767926687)

On the left is code inside the switch-case in the bad scenario when that dummy NOP is not present. On the right is the code with the NOP added.

It is kind of hard to make heads or tails out of it, but one thing I do notice is that in the bad case on the left, the compiler has somehow merged `case 'd':` and `case 'u':` together, since on the left it contains only one call to `chrout_u16(dst);`. On the right however, with that NOP, the second call to `chrout_u16(dst);` is introduced.

**Comment by mysterymath** [comment]
Managed to track this one down; as part of making use of the zero page, the compiler looks for callee-saved imaginary registers and re-writes them to zero page locations that are unique to the function they are used in. This elides the push and pop of those registers to the stack at the beginning  and end of the function.

This is done very late, as instructions that use those opcodes are being lowered into the assembler part of the backend. Inline assembly is handled elsewhere, so this translation was missed. It should be fine to do it there too; anything that uses an imaginary register can use a different zero page location with no trouble.

**Comment by juj** [comment]
Fantastic digging. That sounds like it wasn't related to the varargs part then after all.
