### ISSUE TITLE
Something odd with an infinite loop..

### ISSUE THREAD

**Issue by juj** [llvm-mos/llvm-mos#405]
While testing, I wrote the following program:

`a.cpp`

```c++
int main()
{
  char *b = (char*)0xd020;
  for(;;) *b = *b + 1;
}
```
Building with `mos-c64-clang.bat a.cpp -Oz -o a.out.prg` and disassembling with `llvm-objdump -d a.out.prg.elf`, I get

```
a.out.prg.elf:  file format elf32-mos

Disassembly of section .text:

0000080d <_start>:
     80d: a2 2f         ldx     #$2f
     80f: 86 00         stx     $0                      ; 0x0 <__zp_data_size>
     811: a2 3e         ldx     #$3e
     813: 86 01         stx     $1                      ; 0x1 <__zp_data_size+0x1>

00000815 <__do_init_stack>:
     815: a9 00         lda     #$0
     817: 85 02         sta     $2                      ; 0x2 <__rc0>
     819: a9 c8         lda     #$c8
     81b: 85 03         sta     $3                      ; 0x3 <__rc1>
     81d: 20 32 08      jsr     $832 <__bss_start>                      // ???????????

00000820 <__after_main>:
     820: 4c 28 08      jmp     $828 <__exit_return>

00000823 <_fini>:
     823: a2 3f         ldx     #$3f
     825: 86 01         stx     $1                      ; 0x1 <__zp_data_size+0x1>
     827: 60            rts

00000828 <__exit_return>:
     828: 8d 32 08      sta     $832                    ; 0x832 <__bss_start>
     82b: 20 23 08      jsr     $823 <_fini>
     82e: ad 32 08      lda     $832                    ; 0x832 <__bss_start>
     831: 60            rts
```

The optimizer has optimized away my `*b = *b + 1;`, which I agree to, since I forgot to add `volatile` (a programming error). However, at first I didn't expect it would optimize away my `for(;;) ;` loop, but here it has done so.

Nevertheless, even if there is, there is an oddity on the line marked with the question marks. It is jumping to line $832, labeled with `__bss_start`. I don't quite understand why it would want to do that.

`__bss_start` should contain only zeroes at startup? When I disassemble the code in that location in VICE's hardware monitor, I see the memory is uninitialized: (VICE seems to fill with a repeating pattern `FF FF FF FF 00 00 00 00`)

![image](https://github.com/llvm-mos/llvm-mos/assets/225351/ea1a002e-abeb-47bd-af4c-f4525f3b569c)

and execution does reset to the main screen:

![image](https://github.com/llvm-mos/llvm-mos/assets/225351/c1b0092b-5355-4634-bb3d-31fd6f2e58ff)

--------

In https://discourse.llvm.org/t/clang-optimizing-an-infinite-loop/59116 I found a conversation about this behavior on LLVM, where a commenter refers to https://www.iso-9899.info/n1570.html#6.8.5 :

```
6   An iteration statement whose controlling expression is not a constant expression,[[156]](https://www.iso-9899.info/n1570.html#FOOTNOTE.156) that
    performs no input/output operations, does not access volatile objects, and performs no
    synchronization or atomic operations in its body, controlling expression, or (in the case of
    a for statement) its expression-3, may be assumed by the implementation to
    terminate.[[157]](https://www.iso-9899.info/n1570.html#FOOTNOTE.157)
```

For some reason, the commenter then goes on to refer that the result would be undefined behavior, however at least the paragraph that they cite is unambiguous, and does \*not\* state that the result would be undefined behavior, rather the paragraph very clearly defines what the behavior should be: the optimizer is indeed allowed to assume that the for loop terminates, and optimize it away.

So that makes me wonder whether llvm-mos might be doing something odd here: it seems as if it is optimizing the loop to terminate, but also treating falling outside the loop as unreachable? (which one is it?) This seems incorrect at least on the face of that above paragraph alone.

**Comment by cogwheel** [comment]
> However, at first I didn't expect it would optimize away my `for(;;) ;` loop, but here it has done so.

FWIW: here's a discussion in the FAQ about this: https://llvm-mos.org/wiki/Frequently_asked_questions#Why_is_the_compiler_removing_my_infinite_loops.3F

**Comment by juj** [comment]
Thanks!

Do you know if there is a standards paragraph about the Undefined Behavior? A cited blog article here https://stefansf.de/post/non-termination-considered-harmful/ follows the same logical fallacy: they claim that it is undefined behavior to write code that does not make forward progress, but then cites paragraphs of the standard which bear no mention about this undefined behavior: instead they write

```
This is intended to allow compiler transformations such as removal of empty loops even when termination cannot be proven. 
```
from https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf , but again, there is no mention about undefined behavior, just they define that optimizers are allowed to generate code to assume that all loops will terminate. Jumping from that to UDB does not seem like a logical conclusion.

(I am not saying that the scenario could not be UDB, but at least on the face of the paragraphs from standards as worded do not seem to mention UDB that I could find. It would be odd to first remark that "this is intended to allow compiler to remove empty loops" to define a behavior, but then in actuality make it be Undefined Behavior instead)

I'd be happy to raise this to upstream LLVM, although just wanted to make sure there is nothing llvm-mos specific here first.

**Comment by mysterymath** [comment]
Infinite loops aren't undefined behavior in C; they're only so in C++. The C++ standard section that covers this is 6.9.2.3, forward progress:
https://eel.is/c++draft/intro.progress

The implementation may assume that any thread will eventually do one of the following:
terminate,
make a call to a library I/O function,
perform an access through a volatile glvalue, or
perform a synchronization operation or an atomic operation.

It's not so much that "infinite loops are undefined behavior", it's more than that; it's that code locations that can be proven to cause an infinite loop if reached can be considered unreachable.

Closing; this is a well known behavior of standards-compliant C++ compilers.
