### ISSUE TITLE
"Unsupported physical register copy" when copying between MOSReg1Class

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#41]
I'm getting an assert in MOSInstrInfo::copyPhysRegImpl() when codegen attempts to copy an Anyi1 to another.

It's also not immediately clear what the best way is, to copy the bit back and forth between C, V, A, X, and Y.  I'm not sure whether you intended copies from 1 bit to 8 bit registers, to kill the other 7 bits of the register, when you're copying C or V to an 8 bit type.

The mechanism I imagined, for getting data in and out of P, would be PHP/PLA and PHA/PLP pairs.  I am confused what your strategy is on i1?  Woz stored i1's in the high bit of 8 bit values: https://www.pagetable.com/?p=33

The following can be inserted into postrapseudo.mir to make sure the ALSB<->C cases are handled somehow.  All the i1 copy types should probably be checked though...

```
---
name: alsb_c
# CHECK-LABEL: name: alsb_c
body: |
  bb.0.entry:
    liveins: $c
    renamable $alsb = COPY killed renamable $c, implicit-def $a
...
---
name: c_alsb
# CHECK-LABEL: name: c_alsb
body: |
  bb.0.entry:
    liveins: $c
    renamable $c = COPY killed renamable $alsb
...
```

**Comment by mysterymath** [comment]
Ah, interesting about using the high bit re LSR and BIT. 

No real strategy, making it up as I go along. At the moment, the mechanism for copying values into and out of $alsb is pretty undefined at the moment, and I don't even think what's there is internally consistent. It's more consistent than it used to be at least; this is something I'm still actively hashing out.

It's very unlikely on the outset that PHP/PLA will be a good sequence for extracting values out of P to be stored elsewhere; it takes 2 bytes and 7 cycles before starting to extract the part of P we need, while a  branch to a pair of immediate loads takes 6 bytes and 4 or 5 cycles for the whole thing, and that's the worst case for extracting flag to value. For value to flag, we can get a LSB or MSB into C via ASL and LSR, and V from a MSB via LSR,BIT, etc.

**Comment by mysterymath** [comment]
All possible physreg copies have now been implemented in terms of other types of copies, CMP, or a SelectImm diamond pseudo. Lowering for the SelectImm pseudo isn't yet implemented.
