### ISSUE TITLE
Initial test-suite pass

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#42]
Now that the test-suite is hooked up, a number of examples are currently capable of compiling and running under the simulator. It looks like they broadly don't work, though. We should see what cases are currently capable of compiling, add each of them to an allowlist (or all the others to a denylist), and repair them one by one. This will establish a baseline of working functionality for the compiler.

**Comment by mysterymath** [comment]
In the initial reckoning, it looks like 420 test cases pass, 55 fail, and 1321 fail to compile or are otherwise missing.

**Comment by johnwbyrd** [comment]
I'm surprised that so many tests pass, this early on!  I vaguely recall that at least some of the tests may depend on floating point.

**Comment by mysterymath** [comment]
I'm surprised at how much of printf seems to work, once I fixed a few key issues. LLVM does a remarkable amount of verification and asserting on the inside, so I guess it's actually kinda difficult to get really really broken stuff through that. Just regular amounts of broken so far.

Anecdote:
A bunch of garbage was getting printed after the 0 in printf("%d\n", 0);, but only on the c64. I added a bunch of diagnostic __putchar('X')-es throughout the code, and to my surprise, it looked like the garbage was after printf! I was returning back to basic after I'd walked all over its variable structure, and basic was printing the garbage.

**Comment by mysterymath** [comment]
On second though it's going to be difficult to keep a "working baseline" established while the work of repairing the test suite is underway. Fixing a compilation error can (and has) activated a hundred or so additional test cases, which can create more failures than it's reasonable to fix in the same commit. I'll be attempting to alternate between fixing compilation issues and fixing test executions so that the suit stays "as working as possible", but the actually number of failing tests will likely oscillate.
