### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by AGPX** [llvm-mos/llvm-mos#479]
If you try to compile the following .cpp code with latest version of LLVM-MOS with:

`mos-c64-clang++.bat -Os -o test.prg test.cpp`

you obtain:

```
ld.lld: error: test.prg.lto.o:(function main: .text.main+0x2a): relocation R_MOS_ADDR8 out of range: 65380 is not in [0, 255]; references section '.zp.data'
>>> referenced by ld-temp.o
mos-clang++: error: ld.lld command failed with exit code 1 (use -v to see invocation)
```

Weird facts:

- If you remove the `__NOINLINE__` from the `__getHitChar__` method, the error disappears (but in the original code, more complex that this, this workaround doesn't work);
- The error disappears also with `-O0` (or without specifying `-O`), but returns with `-Os`, `-O1`, `-O2` and `-O3`.

Code:

```
#define __NOINLINE__ __attribute__((noinline))
#define byte unsigned char
#define word unsigned int


const unsigned char *collTbl[25];

class Actor
{
public:
    
    unsigned int    x;
    unsigned char   y; 

    unsigned char  *__hits__;
         
    unsigned int  __getHitLoc__ (const unsigned char hitIx, const signed char ox, const signed char oy) const;
    unsigned char __getHitChar__(const unsigned char hitIx, const signed char ox, const signed char oy) const;
};

unsigned int Actor::__getHitLoc__(const unsigned char hitIx, const signed char ox, const signed char oy) const
{
    const unsigned int  dx = x - (24 - ox);
    const unsigned char dy = y - (50 - oy);

    const unsigned char pos = 1 + (hitIx << 1);
    const signed char *const ptr = &((const signed char *)__hits__)[pos];

    const unsigned char cx = (unsigned char)((dx + ptr[0]) >> 3);
    const unsigned char cy = (unsigned char)((dy + ptr[1]) >> 3);
    return ((cx < 40) && (cy < 25))
        ? (unsigned int)(collTbl[cy] + cx)
        : 0
        ;
}

__NOINLINE__ unsigned char Actor::__getHitChar__(const unsigned char hitIx, const signed char ox, const signed char oy) const
{
    const unsigned int addr = __getHitLoc__(hitIx, ox, oy);
    return (((unsigned char *)(&addr))[1]) ? *((volatile unsigned char *)addr) : 255;
}

class Level00
{
public:
    void pickObjects();

    Actor player;
    byte screenIx;
    word diamondLoc[4];
    byte diamondScreenIx[4];
    static constexpr byte diamondOff[4] = {0,1,40,41};
    

} Level00__i_n_s_t__;

void Level00::pickObjects()
{
    byte c;

    c = this->player.__getHitChar__(3, 0, 0); 
    if ((c >= 190) && (c <= 193))
    {
        word l;
        l = this->player.__getHitLoc__(3, 0, 0) - Level00::diamondOff[c - 190]; 
        for (c = 0; c < 4; ++c)
        {
            if ((this->diamondScreenIx[c] == this->screenIx) && (this->diamondLoc[c] == 0)) {
                this->diamondLoc[c] = l; 
                break;
            }; 
        };
    }; 
}

int main()
{
    
    while (true) {
        Level00__i_n_s_t__.pickObjects();
    }

    return 0;
}
```

**Comment by mysterymath** [comment]
I'm finally done with the LLVM dev meeting and being sick, so I'm taking a look at this one. I've reproduced it on my end; I'll be digging into the details as I get time.

**Comment by mysterymath** [comment]
The offending relocation in the LTO-produced object file looks quite suspicious:
```
0000002a  00000c02 R_MOS_ADDR8            00000000   .zp.data - be
```

**Comment by AGPX** [comment]
> EDIT: Ah, I see that there's a -190 right in the source. I think I have a vague intuition about what's happening now; probably a constant being inappropriately folded into an addressing mode.

That's quite normal for the x86, like `SBB eax, [esi + 190]`, probably the compiler try to use it also for 6502.

**Comment by mysterymath** [comment]
So, I dug into the code, and the issue is that the MIR->Assembly pass makes the decision about whether to use 8-bit or 16-bit addressing based on whether the target symbol is in the zero page. That simple decision is incorrect in this case; even though the eventual target is in the zero page, a 16-bit subtraction is folded into the addressing calculation,  and truncating that calculation to 8 bits is incorrect.

I'll need to spend some time thinking about what exactly the criteria are for safely using 8-bit addressing. Once we have those criteria, the fix is relatively simple: it would just tell the assembler to use 16-bit addressing for all other cases.

**Comment by mysterymath** [comment]
It's not fixed yet; this was just half of a fix.
