### ISSUE TITLE
"ld: unknown options: --version-script" when compiling llvm-mos with MacOS

### ISSUE THREAD

**Issue by pr1metine** [llvm-mos/llvm-mos#482]
[This commit from upstream](https://github.com/llvm/llvm-project/commit/944478dd62a78f6bb43d4da210643affcc4584b6) causes compilation of LLVM-MOS to fail on MacOS. It tries to compile `lib/libclang-cpp.dylib` with the `--version-script` linker flag (which Apple Clang does not support).

This issue has already been fixed upstream with [this commit](https://github.com/llvm/llvm-project/commit/eaa0a21d21962280dc2c03a09152510f6162a576). I suggest we pull this commit as soon as possible.

**Comment by pr1metine** [comment]
?

**Comment by mysterymath** [comment]
Resolved with the latest merge.
