### ISSUE TITLE
Fill out instruction sets for 65c02, 65ce02, 65816, and other compatibles

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#54]
Although I've sketched in an outline of processor features at https://github.com/llvm-mos/llvm-mos/blob/main/llvm/lib/Target/MOS/MOSDevices.td , it needs to be fleshed out with actual new instructions in MOSInstr*.td, and test cases added to the assembler for each of these variants.

A good overview of 65xx variants is at https://docs.mamedev.org/techspecs/m6502.html .

**Comment by mlund** [comment]
Some additional processor information that may be useful:

- https://gitlab.com/jespergravgaard/kickassembler65ce02.
- https://airtable.com/shrRRDDvm3dvzV2Y1

(The 45GS02 would be particularly interesting for the sdk's `mega65` target.)

**Comment by mlund** [comment]
Issue seems related to #94.

**Comment by matthiaskramm** [comment]
For 6502x, good sources are
http://www.oxyron.de/html/opcodes02.html
https://csdb.dk/getinternalfile.php/222714/NoMoreSecrets-NMOS6510UnintendedOpcodes-20212412.pdf 
https://www.pagetable.com/?p=39
