### ISSUE TITLE
Can't join Slack

### ISSUE THREAD

**Issue by Serentty** [llvm-mos/llvm-mos#55]
Apparently, a Gigantic Software email address is required to join the Slack workspace, so it's not possible to join, despite the fact that the wiki invites everyone to do so. Is there another way to get in?

**Comment by johnwbyrd** [comment]
D'oh, let me fix that.

**Comment by johnwbyrd** [comment]
Could you please verify that the link on llvm-mos.org permits you to sign up now?  Thank you very much.

**Comment by Serentty** [comment]
It's now possible to join. Thanks!
