### ISSUE TITLE
Automated release for llvm-mos-sdk

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#56]
With the SDK rework, the original test automation didn't come along for the ride.

This needs to be reestablished, ideally triggered on changes both to this repo and successful prerelease of the compiler repo.

We shouldn't need to run any tests for this; we can separate out qualifying releases from our continuous build, since it's a cross-repo concern. Eventually we'll probably want llvm-test-suite to automatically trigger whenever llvm-mos or llvm-mos-sdk pushes.

**Comment by johnwbyrd** [comment]
Now that the SDK has the features you intended in there, I would like you to reconsider permitting me to refactor your work on the SDK and adding a Github runner as part of an automated build.  I would like to retain all the functionality you have created, including the configuration file concept, while refactoring the SDK to make the directory structure of it.

**Comment by mysterymath** [comment]
Sure, feel free.

I'll give a quick heads up to be careful with --gc-sections, which I've needed to enable by default. Any section need to either contain a referenced symbol or the 'R' ELF flag; otherwise it'll be stripped. LTO includes all possible libcalls in the binary by default; so we need section GC to strip out all the cruft. It's also probably a sensible default on a resource-constrained compiler, but we'll probably want to make a note of it in the docs.

I should also mention: the one other property that I'd like to retain is that the shipped artifact is a low-dependency collection of files, like the llvm-mos artifact currently is. It'll be nice for the llvm-test-suite automation to be able to just download and unzip llvm-mos and llvm-mos-sdk right next to each other (both fully built), then configure the cmake build for llvm-test-suite to point to each, without further futzing with them. That'll also mirror the expected user behavior for a v0.1.0 release: unzip the compiler, unzip the SDK, go nuts!

It'd also be nice if there were a way to build a combined zip with the two together; I imagine that'd be the typical download.

**Comment by mysterymath** [comment]
I've managed to whip up a simple github actions flow to build prerelease distribution packages.

I'm going to put a couple more layers of polish on; just a few minor things there and there. But, we're getting very close to something releasable, I think.
