### ISSUE TITLE
Automated llvm-mos release packages do not include clang headers

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#58]
Clang comes with a suite of headers that form a major portion of the freestanding C implementation requirements.

I extracted the binaries to "/home/mysterymath/foo/c", and this appears to be then taken by clang as the "InstalledDir". In turn, it then looks for these headers in "/home/mysterymath/foo/lib/clang/13.0.0/include".

These do need to be included with the compiler for it to comply with the requirements for a freestanding C implementation, and the SDK needs them to work too (stdarg.h is in there, which is needed for va_list).

**Comment by johnwbyrd** [comment]
Should be fixed in llvm-mos/continuous-release now.  Try extracting fresh bits from any release.
