### ISSUE TITLE
fuzix

### ISSUE THREAD

**Issue by ojej** [llvm-mos/llvm-mos#59]
Is possible compiling fuzix using this compiler? or only some programs
https://github.com/EtchedPixels/FUZIX

**Comment by mysterymath** [comment]
We're not cc65-compatible, so if the project uses cc65-specific features for its 6502 mode, it'll need to be ported to work under clang. We're in a very pre-release state at the moment; the compiler has both missing/broken functionality and serious performance issues we need to work through before our initial public release.

**Comment by ojej** [comment]
from link
_Kernel boots to userspace on 6303, 6502, 65C816, 68000, 6803, 6809, 8080, 8085, MSP430 (bitrotted) and Z80/Z180_
