### ISSUE TITLE
LLVM-MOS ZIPs are "tarbombs"

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#65]
The pre-release ZIPs extract a considerable number of subdirectories into the directory containing the zip if extracted with the default options. 

This is generally considered a packaging faux pas (called a "tar bomb"), as it explodes files over the current directory, and there's no easy way to clean them up afterwards.

Instead, the zip should contain a llvm-mos directory that contains all other files and subdirectories.

**Comment by johnwbyrd** [comment]
Seems reasonable.  Let me see what I can do.

**Comment by johnwbyrd** [comment]
Done, LGTM
