### ISSUE TITLE
unable to legalize instruction: %33:_(s16) = G_USUBSAT

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos#69]
After this small change in my rust demo: https://github.com/mrk-its/llvm-mos-ferris-demo/commit/b1ec4da58f7fe6f806a7d90817f55ebb09d2bbb8 llvm throws:

```
LLVM ERROR: unable to legalize instruction: %35:_(s16) = G_USUBSAT %25:_, %34:_ (in function: _ZN6ferris12update_dlist17hfa3e0492d34a5ddcE)
```
to reproduce it without rust I'm attaching list of *.ll files with Makefile

[clang-mos-unable-to-legalize-usubsat.tar.gz](https://github.com/llvm-mos/llvm-mos/files/6729456/clang-mos-unable-to-legalize-usubsat.tar.gz)

**Comment by mysterymath** [comment]
Fixed by 7cc9ed7
