### ISSUE TITLE
G_USUBSAT compiles, but doesn't work

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos#70]
After https://github.com/llvm-mos/llvm-mos/commit/7cc9ed7531d664fd4e2b268841df2b8a9df8373a I noticed that my rust demo compiled, but stopped working. To investigate it I created following test program doing some saturing arithmetic:
[llvm-mos-sat-test.tar.gz](https://github.com/llvm-mos/llvm-mos/files/6743981/llvm-mos-sat-test.tar.gz) 

it generates following output:
```
uadd_sat_8(0xf0, 0x20) = 0xff
uadd_sat_16(0xf000, 0x2000) = 0xffff
uadd_sat_32(0xf0000000, 0x20000000) = 0xffffffff
usub_sat_8(0x10, 0x20) = 0xf0
usub_sat_16(0x1000, 0x2000) = 0xf000
usub_sat_32(0x10000000, 0x20000000) = 0xf0000000
ushl_sat_8(0x80, 0x1) = 0xff
ushl_sat_16(0x8000, 0x1) = 0xffff
ushl_sat_32(0x80000000, 0x1) = 0xffffffff
sshl_sat_8(0x40, 0x3) = 0x7f
sshl_sat_16(0x4000, 0x3) = 0x7fff
sshl_sat_32(0x40000000, 0x1) = 0x7fffffff
```
and reveals few things:
* G_USUBSAT doesn't work (for example usub_sat_8(0x10, 0x20) == 0xf0)
* G_SADDSAT doesn't compile, it throws `unable to legalize instruction: %3:_(s8), %4:_(s1) = G_SADDO` now
* G_SSUBSAT doesn't compile, it thorws `unable to legalize instruction: %3:_(s8), %4:_(s1) = G_SSUBO` now

remaining operations seem to work.

So maybe we should remove legalization at least of `G_USUBSAT` as it is better to not compile than to generate not working assembly?

**Comment by mysterymath** [comment]
Fixed G_USUBSAT with 32b8c0b.

G_SADDO and G_SSUBO are harder; I'll have to teach the compiler about how to use the overflow flag for this (and figure it out for myself at the same time). I'll hit those next.
