### ISSUE TITLE
error on linux

### ISSUE THREAD

**Issue by 0xtrzy** [llvm-mos/llvm-mos#74]
[ 98%] Linking CXX executable ../../bin/dsymutil
[ 98%] Linking CXX executable ../../bin/bugpoint
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/lli/CMakeFiles/lli.dir/build.make:171: bin/lli] Błąd 1
make[2]: *** Kasuję plik 'bin/lli'
make[1]: *** [CMakeFiles/Makefile2:28110: tools/lli/CMakeFiles/lli.dir/all] Błąd 2
make[1]: *** Oczekiwanie na niezakończone zadania....
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/llvm-exegesis/CMakeFiles/llvm-exegesis.dir/build.make:153: bin/llvm-exegesis] Błąd 1
make[2]: *** Kasuję plik 'bin/llvm-exegesis'
make[1]: *** [CMakeFiles/Makefile2:30076: tools/llvm-exegesis/CMakeFiles/llvm-exegesis.dir/all] Błąd 2
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/llvm-gsymutil/CMakeFiles/llvm-gsymutil.dir/build.make:251: bin/llvm-gsymutil] Błąd 1
make[2]: *** Kasuję plik 'bin/llvm-gsymutil'
make[1]: *** [CMakeFiles/Makefile2:30724: tools/llvm-gsymutil/CMakeFiles/llvm-gsymutil.dir/all] Błąd 2
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/llc/CMakeFiles/llc.dir/build.make:231: bin/llc] Błąd 1
make[2]: *** Kasuję plik 'bin/llc'
make[1]: *** [CMakeFiles/Makefile2:27977: tools/llc/CMakeFiles/llc.dir/all] Błąd 2
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/dsymutil/CMakeFiles/dsymutil.dir/build.make:333: bin/dsymutil] Błąd 1
make[2]: *** Kasuję plik 'bin/dsymutil'
make[1]: *** [CMakeFiles/Makefile2:27736: tools/dsymutil/CMakeFiles/dsymutil.dir/all] Błąd 2
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/bugpoint/CMakeFiles/bugpoint.dir/build.make:350: bin/bugpoint] Błąd 1
make[2]: *** Kasuję plik 'bin/bugpoint'
make[1]: *** [CMakeFiles/Makefile2:27530: tools/bugpoint/CMakeFiles/bugpoint.dir/all] Błąd 2
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/llvm-lto/CMakeFiles/llvm-lto.dir/build.make:233: bin/llvm-lto] Błąd 1
make[2]: *** Kasuję plik 'bin/llvm-lto'
make[1]: *** [CMakeFiles/Makefile2:27253: tools/llvm-lto/CMakeFiles/llvm-lto.dir/all] Błąd 2
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/lto/CMakeFiles/LTO.dir/build.make:272: lib/libLTO.so.12git] Błąd 1
make[2]: *** Kasuję plik 'lib/libLTO.so.12git'
make[1]: *** [CMakeFiles/Makefile2:26572: tools/lto/CMakeFiles/LTO.dir/all] Błąd 2
collect2: fatal error: ld terminated with signal 9 [Unicestwiony]
compilation terminated.
make[2]: *** [tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/build.make:237: bin/llvm-dwp] Błąd 1
make[2]: *** Kasuję plik 'bin/llvm-dwp'
make[1]: *** [CMakeFiles/Makefile2:29863: tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/all] Błąd 2
[ 98%] Built target llvm-c-test

**Comment by johnwbyrd** [comment]
That looks like an out of memory error to me.  You'll need a machine with more RAM.
