### ISSUE TITLE
Move Responsibility for Stack Pointer Atomicity to Interrupt Handlers

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos#77]
Currently, functions are responsible for ensuring that whenever they adjust  the value of SP is never seen to decrease below the highest address containing live values. Achieving this in practice requires a PHA/PLA pair to save the low sum of the offset of SP so that the high byte can be written before the low byte. This places a 7 cycle burden on every function that uses the soft stack, including interrupt handlers. Worse, this may waste 256 bytes of stack in a highly non-deterministic fashion, which makes it harder to reason about stack usage in a very memory-constrained environment.

@vbc pointed out that the nondeterminism would produce considerable practical debugging and reproducability challenges; I find this a compelling argument.

Instead, the burden for this can be shifted onto the interrupt handler. Functions would only be required to ensure that SP is not more than 1 page below live values, and interrupt handlers would be required to summarily increase SP by one page. This wastes 256 bytes of stack every time an interrupt is invoked, but it does so deterministically.

Doing it this way makes code easier to debug for space usage, and allows developers to set up their own ISR prologues/epilogues that use dedicated stacks. With this, developers can avoid paying any cost due to this concern with some additional effort, but they still don't have to if they don't want to.

Impact of wasting this space can be mitigated by having a 1-page red zone above SP; this is a considerable amount of additional work though, and is outside the scope of this issue.

**Comment by chorman0773** [comment]
The redzone would have to start 4 bytes after SP, since the hardware handling of the interrupt itself clobbers those 4 bytes, long before any interrupt handler can do anything about it.

**Comment by mysterymath** [comment]
Ah, this is for the soft stack pointer; llvm-mos treats hard stack totally separately.

**Comment by mysterymath** [comment]
Fixed by 5139150
