### ISSUE TITLE
Feature request: flag output from inline asm

### ISSUE THREAD

**Issue by gergoerdi** [llvm-mos/llvm-mos#85]
GCC and Clang on some architectures supports [flag output operands](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#FlagOutputOperands). If this was supported by LLVM-MOS, we could write e.g.:

```
bool k_open()
{
    bool carry;

    __attribute__((leaf)) asm(
        "jsr $ffc0"
        : "=@ccc" (carry)
        :
        : "p"
        );
    return !carry;
}
```

Currently, this (understandably) fails with:

```
src/kernal.c:36:11: error: invalid output constraint '=@ccc' in asm
        : "=@ccc" (carry)
          ^
```

**Comment by mysterymath** [comment]
This will be fairly easy to support for C and V, but fairly difficult to support for N and Z. Due to the number of instructions that clobber N and Z, we don't model them directly, otherwise it's very difficult to insert code without worrying about clobbering them. Do you have a particular use case in mind?

**Comment by gergoerdi** [comment]
The use case I have in mind is for marshalling error conditions from KERNAL routines, like in [this example](https://github.com/gergoerdi/rust-mos-chip8/blob/02181faa107efff9e46aa179b3ad058078b9c4f5/src/kernal.c#L30-L40):

```
bool k_open()
{
    // TODO: error checking: if Carry flag is set, then error
    __attribute__((leaf)) asm volatile (
        "jsr $ffc0"
        :
        :
        : "p"
        );
    return true;
}
```

**Comment by mysterymath** [comment]
Done for both input and output for C and V; given the way the compiler works, N and Z would be a considerable ask beyond that needed for the use-case described here. Closing for now, feel free to reopen if N and Z end up needed.
