### ISSUE TITLE
Finish 65C02 assembler support

### ISSUE THREAD

**Issue by johnwbyrd** [llvm-mos/llvm-mos#94]
The 65C02 is partially supported as of this writing in the assembler.  The entirety of the additional 'C02 instruction set should be supported, and appropriate test cases added.

**Comment by gandhi56** [comment]
What 65c02 opcodes are missing?

**Comment by mlund** [comment]
I think almost all 65c02 opcodes will be there when #192 is ready (still need a bit of work).

**Comment by johnwbyrd** [comment]
Closing with the merge of #192 .
